export const SECTION_IDS = {
  general: "general-settings",
  systemAccess: "system-access",
  workflow: "workflow-settings",
  ai: "ai-settings",
  providers: "provider-settings",
  telemetry: "telemetry",
  plugins: "plugins",
  integrations: "integrations",
  connections: "connections",
  storage: "storage-settings",
  agentPermissions: "agent-permissions",
  toolsMcp: "tools-mcp",
  experiments: "experiments",
  dangerZone: "danger-zone",
  chatAgent: "chat-agent-settings",
  aiCoder: "ai-coder-settings",
  imageAgent: "image-agent-settings",
  videoAgent: "video-agent-settings",
  helix: "helix-agent-settings",
  modelRoles: "model-roles-settings",
  jarvis: "jarvis-settings",
} as const;

export const SETTING_IDS = {
  theme: "setting-theme",
  appLayout: "setting-app-layout",
  chatAgentTerminalAccess: "setting-chat-agent-terminal-access",
  chatAgentBrowserAccess: "setting-chat-agent-browser-access",
  chatAgentComputerAccess: "setting-chat-agent-computer-access",
  zoom: "setting-zoom",
  autoUpdate: "setting-auto-update",
  releaseChannel: "setting-release-channel",
  runtimeMode: "setting-runtime-mode",
  nodePath: "setting-node-path",
  customAppsFolder: "setting-custom-apps-folder",
  defaultChatMode: "setting-default-chat-mode",
  autoApprove: "setting-auto-approve",
  autoFix: "setting-auto-fix",
  autoExpandPreview: "setting-auto-expand-preview",
  keepPreviewsRunning: "setting-keep-previews-running",
  chatEventNotification: "setting-chat-event-notification",
  thinkingBudget: "setting-thinking-budget",
  maxChatTurns: "setting-max-chat-turns",
  maxToolCallSteps: "setting-max-tool-call-steps",
  contextCompaction: "setting-context-compaction",
  telemetry: "setting-telemetry",
  github: "setting-github",
  vercel: "setting-vercel",
  lovable: "setting-lovable",
  canva: "setting-canva",
  travelSearch: "setting-travel-search",
  duckDuckGo: "setting-duckduckgo",
  coinGecko: "setting-coingecko",
  weather: "setting-weather",
  maps: "setting-maps",
  skyscanner: "setting-skyscanner",
  amadeus: "setting-amadeus",
  duffel: "setting-duffel",
  supabase: "setting-supabase",
  facebook: "setting-facebook",
  xIntegration: "setting-x",
  storageDestination: "setting-storage-destination",
  localVault: "setting-local-vault",
  vercelBlob: "setting-vercel-blob",
  nativeGit: "setting-native-git",
  enableCloudSandbox: "setting-enable-cloud-sandbox",
  enableSandboxScriptExecution: "setting-enable-sandbox-script-execution",
  blockUnsafeNpmPackages: "setting-block-unsafe-npm-packages",
  enableMcpServersForBuildMode: "setting-enable-mcp-servers-for-build-mode",
  enableSelectAppFromHomeChatInput:
    "setting-enable-select-app-from-home-chat-input",
  reset: "setting-reset",
  chatAgentModel: "setting-chat-agent-model",
  chatAgentMcpServers: "setting-chat-agent-mcp-servers",
  chatAgentMcpTools: "setting-chat-agent-mcp-tools",
  chatAgentMcpWorkflows: "setting-chat-agent-mcp-workflows",
  aiCoderProvider: "setting-ai-coder-provider",
  aiCoderEndpoint: "setting-ai-coder-endpoint",
  aiCoderApiKey: "setting-ai-coder-api-key",
  aiCoderFeatures: "setting-ai-coder-features",
  imageAgentModel: "setting-image-agent-model",
  videoAgentApiKey: "setting-video-agent-api-key",
  videoAgentModel: "setting-video-agent-model",
  helixGatewayKey: "setting-helix-gateway-key",
  modelRoleChat: "setting-model-role-chat",
  modelRoleImage: "setting-model-role-image",
  modelRoleCoding: "setting-model-role-coding",
  modelRoleVideo: "setting-model-role-video",
  modelRoleEmbeddings: "setting-model-role-embeddings",
  modelRoleOcr: "setting-model-role-ocr",
  jarvisChatReadAloud: "setting-jarvis-chat-read-aloud",
} as const;

type SearchableSettingItem = {
  id: string;
  label: string;
  description: string;
  keywords: string[];
  sectionId: string;
  sectionLabel: string;
};

export const SETTINGS_SEARCH_INDEX: SearchableSettingItem[] = [
  // Voice Assistant
  {
    id: "setting-jarvis-elevenlabs-key",
    label: "ElevenLabs API key",
    description:
      "Credential for Meta Human OS speech-to-text and text-to-speech",
    keywords: ["elevenlabs", "voice", "jarvis", "api key", "speech", "tts"],
    sectionId: SECTION_IDS.jarvis,
    sectionLabel: "Voice Assistant",
  },
  {
    id: "setting-jarvis-voice",
    label: "Meta Human OS voice",
    description: "Voice ID, speed, stability and similarity for spoken replies",
    keywords: ["voice", "jarvis", "speed", "stability", "similarity", "speak"],
    sectionId: SECTION_IDS.jarvis,
    sectionLabel: "Voice Assistant",
  },
  {
    id: SETTING_IDS.jarvisChatReadAloud,
    label: "Chat read-aloud voice",
    description:
      "Choose the system voice or an ElevenLabs voice for AI messages",
    keywords: [
      "chat",
      "read aloud",
      "elevenlabs",
      "voice provider",
      "tts",
      "audio",
    ],
    sectionId: SECTION_IDS.jarvis,
    sectionLabel: "Voice Assistant",
  },
  {
    id: "setting-jarvis-model",
    label: "Meta Human OS model",
    description: "Which connected model powers voice conversations",
    keywords: ["jarvis", "model", "voice model", "routing", "local model"],
    sectionId: SECTION_IDS.jarvis,
    sectionLabel: "Voice Assistant",
  },
  // System
  {
    id: SETTING_IDS.theme,
    label: "Theme",
    description: "Switch between system, light, and dark mode",
    keywords: ["dark mode", "light mode", "appearance", "color", "system"],
    sectionId: SECTION_IDS.general,
    sectionLabel: "System",
  },
  {
    id: SETTING_IDS.zoom,
    label: "Zoom Level",
    description: "Adjust the zoom level to make content easier to read",
    keywords: ["font size", "magnify", "scale", "accessibility", "zoom"],
    sectionId: SECTION_IDS.general,
    sectionLabel: "System",
  },
  {
    id: SETTING_IDS.appLayout,
    label: "App Layout",
    description: "Switch the application window between landscape and portrait",
    keywords: ["portrait", "landscape", "orientation", "window", "layout"],
    sectionId: SECTION_IDS.general,
    sectionLabel: "System",
  },
  {
    id: SETTING_IDS.chatAgentTerminalAccess,
    label: "Chat Agent terminal access",
    description: "Allow confirmed terminal commands from Chat Agent",
    keywords: ["terminal", "shell", "command", "chat agent", "system access"],
    sectionId: SECTION_IDS.systemAccess,
    sectionLabel: "System Access",
  },
  {
    id: SETTING_IDS.chatAgentBrowserAccess,
    label: "Chat Agent browser use",
    description: "Allow Chat Agent to read web pages",
    keywords: ["browser", "web", "page", "chat agent", "system access"],
    sectionId: SECTION_IDS.systemAccess,
    sectionLabel: "System Access",
  },
  {
    id: SETTING_IDS.chatAgentComputerAccess,
    label: "Chat Agent computer use",
    description: "Allow confirmed computer actions from Chat Agent",
    keywords: ["computer", "click", "type", "macos", "chat agent", "system"],
    sectionId: SECTION_IDS.systemAccess,
    sectionLabel: "System Access",
  },

  // AI Settings
  {
    id: SECTION_IDS.modelRoles,
    label: "Model Roles",
    description:
      "Assign compatible models to chat, image, coding, video, embeddings, and OCR",
    keywords: [
      "models",
      "roles",
      "chat",
      "image",
      "coding",
      "video",
      "embeddings",
      "ocr",
      "ollama",
      "lm studio",
    ],
    sectionId: SECTION_IDS.modelRoles,
    sectionLabel: "Model Roles",
  },
  ...[
    ["modelRoleChat", "Chat", "conversation and tool-assisted tasks"],
    ["modelRoleImage", "Image Generation", "image creation and editing"],
    ["modelRoleCoding", "Coding", "code generation and debugging"],
    ["modelRoleVideo", "Video Generation", "video creation"],
    ["modelRoleEmbeddings", "Embeddings", "vector search and retrieval"],
    ["modelRoleOcr", "OCR", "reading text from images"],
  ].map(([id, label, description]) => ({
    id: SETTING_IDS[id as keyof typeof SETTING_IDS],
    label: `${label} model role`,
    description: `Choose a compatible model for ${description}`,
    keywords: [label.toLowerCase(), "model", "role", "auto select"],
    sectionId: SECTION_IDS.modelRoles,
    sectionLabel: "Model Roles",
  })),
  {
    id: SETTING_IDS.thinkingBudget,
    label: "Thinking Budget",
    description: "Set the AI thinking token budget",
    keywords: ["thinking", "tokens", "budget", "reasoning", "ai"],
    sectionId: SECTION_IDS.ai,
    sectionLabel: "AI",
  },
  {
    id: SETTING_IDS.maxChatTurns,
    label: "Max Chat Turns",
    description: "Set the maximum number of conversation turns",
    keywords: ["turns", "max", "conversation", "limit", "chat"],
    sectionId: SECTION_IDS.ai,
    sectionLabel: "AI",
  },
  {
    id: SETTING_IDS.maxToolCallSteps,
    label: "Max Tool Calls (Agent)",
    description: "Set the maximum number of tool calls for local agent mode",
    keywords: [
      "tool",
      "calls",
      "max",
      "limit",
      "agent",
      "steps",
      "local",
      "loop",
    ],
    sectionId: SECTION_IDS.ai,
    sectionLabel: "AI",
  },
  {
    id: SETTING_IDS.contextCompaction,
    label: "Context Compaction",
    description:
      "Automatically compact long conversations to stay within context limits",
    keywords: [
      "context",
      "compaction",
      "compact",
      "summarize",
      "tokens",
      "window",
      "memory",
    ],
    sectionId: SECTION_IDS.ai,
    sectionLabel: "AI",
  },
  {
    id: SETTING_IDS.chatAgentModel,
    label: "Chat Agent model",
    description:
      "Choose the inference model for Chat Agent (OpenRouter, OpenAI, or LM Studio)",
    keywords: [
      "chat agent",
      "chat",
      "agent",
      "model",
      "openrouter",
      "openai",
      "lm studio",
      "lmstudio",
      "inference",
    ],
    sectionId: SECTION_IDS.chatAgent,
    sectionLabel: "Chat Agent",
  },
  {
    id: SECTION_IDS.chatAgent,
    label: "Chat Agent",
    description: "Configure the Chat Agent inference model",
    keywords: ["chat agent", "chat", "agent", "model", "llm"],
    sectionId: SECTION_IDS.chatAgent,
    sectionLabel: "Chat Agent",
  },

  // Image generation used by Chat
  {
    id: SETTING_IDS.imageAgentModel,
    label: "Image generation model",
    description: "Choose the image model used when generating inside Chat",
    keywords: [
      "image",
      "chat",
      "model",
      "openrouter",
      "nano banana",
      "gemini",
      "flux",
      "generate",
      "picture",
    ],
    sectionId: SECTION_IDS.imageAgent,
    sectionLabel: "Model Roles",
  },

  // Video generation used by Chat
  {
    id: SETTING_IDS.videoAgentApiKey,
    label: "fal API key",
    description: "API key for the fal.ai video generation provider",
    keywords: ["video", "chat", "fal", "fal.ai", "api key", "key"],
    sectionId: SECTION_IDS.videoAgent,
    sectionLabel: "Model Roles",
  },
  {
    id: SETTING_IDS.videoAgentModel,
    label: "Video generation model",
    description: "Default fal.ai model used for video requests in Chat",
    keywords: [
      "video",
      "chat",
      "model",
      "fal",
      "kling",
      "luma",
      "minimax",
      "shorts",
      "reels",
      "generate",
    ],
    sectionId: SECTION_IDS.videoAgent,
    sectionLabel: "Model Roles",
  },

  // Helix Coding Agent
  {
    id: SETTING_IDS.helixGatewayKey,
    label: "Vercel AI Gateway token",
    description:
      "API key for the Vercel AI Gateway used by the Helix coding agent",
    keywords: [
      "helix",
      "vercel",
      "gateway",
      "ai gateway",
      "token",
      "api key",
      "coding agent",
    ],
    sectionId: SECTION_IDS.helix,
    sectionLabel: "Helix Coding Agent",
  },

  // Provider Settings
  {
    id: SECTION_IDS.providers,
    label: "Model Providers",
    description: "Configure AI model providers and API keys",
    keywords: [
      "provider",
      "model",
      "api key",
      "openai",
      "anthropic",
      "claude",
      "gpt",
      "gemini",
      "llm",
    ],
    sectionId: SECTION_IDS.providers,
    sectionLabel: "Model Providers",
  },

  // Integrations
  {
    id: SETTING_IDS.github,
    label: "GitHub Integration",
    description: "Connect your GitHub account",
    keywords: ["github", "git", "integration", "connect", "account"],
    sectionId: SECTION_IDS.plugins,
    sectionLabel: "Plugins",
  },
  {
    id: SETTING_IDS.vercel,
    label: "Vercel Integration",
    description: "Connect your Vercel account for deployments",
    keywords: ["vercel", "deploy", "integration", "hosting", "connect"],
    sectionId: SECTION_IDS.plugins,
    sectionLabel: "Plugins",
  },
  {
    id: SETTING_IDS.lovable,
    label: "Lovable MCP",
    description: "Connect Lovable projects, builds, and published websites",
    keywords: [
      "lovable",
      "mcp",
      "plugin",
      "website",
      "deploy",
      "project",
      "agent",
    ],
    sectionId: SECTION_IDS.plugins,
    sectionLabel: "Plugins",
  },
  {
    id: SETTING_IDS.canva,
    label: "Canva MCP",
    description: "Create, edit, search and export Canva designs",
    keywords: [
      "canva",
      "mcp",
      "plugin",
      "design",
      "presentation",
      "slides",
      "export",
    ],
    sectionId: SECTION_IDS.plugins,
    sectionLabel: "Plugins",
  },
  {
    id: SETTING_IDS.travelSearch,
    label: "Travel Search",
    description: "Create keyless flight searches from Chat Agent",
    keywords: ["travel", "flight", "fare", "skyscanner", "free", "no api key"],
    sectionId: SECTION_IDS.plugins,
    sectionLabel: "Plugins",
  },
  {
    id: SETTING_IDS.duckDuckGo,
    label: "DuckDuckGo Search",
    description: "Enable keyless web lookups for Chat Agent",
    keywords: [
      "duckduckgo",
      "web",
      "search",
      "instant answers",
      "chat agent",
      "free",
    ],
    sectionId: SECTION_IDS.plugins,
    sectionLabel: "Plugins",
  },
  {
    id: SETTING_IDS.coinGecko,
    label: "CoinGecko",
    description: "Enable cryptocurrency price and market searches",
    keywords: ["coingecko", "crypto", "bitcoin", "price", "market", "api"],
    sectionId: SECTION_IDS.plugins,
    sectionLabel: "Plugins",
  },
  {
    id: SETTING_IDS.weather,
    label: "Open-Meteo Weather",
    description: "Enable live weather and forecasts for Chat Agent",
    keywords: [
      "weather",
      "forecast",
      "temperature",
      "rain",
      "open-meteo",
      "free",
      "no api key",
    ],
    sectionId: SECTION_IDS.plugins,
    sectionLabel: "Plugins",
  },
  {
    id: SETTING_IDS.maps,
    label: "Maps",
    description: "Enable place search and interactive maps for Chat Agent",
    keywords: [
      "maps",
      "places",
      "location",
      "maplibre",
      "openfreemap",
      "geocoding",
      "free",
      "no api key",
    ],
    sectionId: SECTION_IDS.plugins,
    sectionLabel: "Plugins",
  },
  {
    id: SETTING_IDS.skyscanner,
    label: "Skyscanner",
    description: "Connect live flight-price search",
    keywords: ["skyscanner", "flight", "travel", "airline", "price", "api key"],
    sectionId: SECTION_IDS.plugins,
    sectionLabel: "Plugins",
  },
  {
    id: SETTING_IDS.amadeus,
    label: "Amadeus Flight Offers",
    description: "Search structured flight offers with a free API quota",
    keywords: ["amadeus", "flight", "travel", "airline", "fare", "free quota"],
    sectionId: SECTION_IDS.plugins,
    sectionLabel: "Plugins",
  },
  {
    id: SETTING_IDS.duffel,
    label: "Duffel Sandbox",
    description: "Test flight search with simulated sandbox offers",
    keywords: ["duffel", "flight", "sandbox", "test", "simulated", "airline"],
    sectionId: SECTION_IDS.plugins,
    sectionLabel: "Plugins",
  },
  {
    id: SETTING_IDS.supabase,
    label: "Supabase Connection",
    description: "Connect your Supabase project",
    keywords: [
      "supabase",
      "database",
      "integration",
      "backend",
      "connect",
      "connection",
      "postgres",
    ],
    sectionId: SECTION_IDS.connections,
    sectionLabel: "Integrations",
  },
  {
    id: SETTING_IDS.facebook,
    label: "Facebook",
    description: "Connect a Facebook Page for social publishing",
    keywords: ["facebook", "meta", "page", "social", "publishing"],
    sectionId: SECTION_IDS.integrations,
    sectionLabel: "Integrations",
  },
  {
    id: SETTING_IDS.xIntegration,
    label: "X",
    description: "Connect an X account for social publishing",
    keywords: ["x", "twitter", "social", "publishing"],
    sectionId: SECTION_IDS.integrations,
    sectionLabel: "Integrations",
  },
  {
    id: SETTING_IDS.storageDestination,
    label: "Storage destination",
    description: "Choose local vault or Vercel Blob cloud storage",
    keywords: ["storage", "local", "cloud", "vault", "privacy"],
    sectionId: SECTION_IDS.storage,
    sectionLabel: "Storage",
  },
  {
    id: SETTING_IDS.localVault,
    label: "Local Vault",
    description: "Store conversations, media and notes as Obsidian Markdown",
    keywords: ["obsidian", "markdown", "folder", "images", "notes"],
    sectionId: SECTION_IDS.storage,
    sectionLabel: "Storage",
  },
  {
    id: SETTING_IDS.vercelBlob,
    label: "Vercel Blob",
    description: "Connect cloud storage with a Blob read/write token",
    keywords: ["vercel", "blob", "token", "cloud", "api"],
    sectionId: SECTION_IDS.storage,
    sectionLabel: "Storage",
  },

  // Tool Permissions
  {
    id: SECTION_IDS.agentPermissions,
    label: "Tool Permissions",
    description: "Configure permissions for built-in tools",
    keywords: [
      "agent",
      "permissions",
      "tools",
      "approve",
      "allow",
      "consent",
      "pro",
      "terminal",
      "files",
      "folders",
      "directories",
      "vault",
      "obsidian",
    ],
    sectionId: SECTION_IDS.agentPermissions,
    sectionLabel: "Tool Permissions",
  },

  // Tools (MCP)
  {
    id: SECTION_IDS.toolsMcp,
    label: "Tools (MCP)",
    description:
      "Configure MCP servers, headers, tool consent, and Chat Agent access",
    keywords: [
      "mcp",
      "tools",
      "server",
      "model context protocol",
      "environment",
      "n8n",
      "headers",
      "chat agent",
    ],
    sectionId: SECTION_IDS.toolsMcp,
    sectionLabel: "Tools (MCP)",
  },
  {
    id: SETTING_IDS.chatAgentMcpServers,
    label: "Chat Agent MCP servers",
    description: "Choose which configured MCP servers Chat Agent can use",
    keywords: ["mcp", "chat agent", "tools", "server", "n8n", "select"],
    sectionId: SECTION_IDS.toolsMcp,
    sectionLabel: "Tools (MCP)",
  },
  {
    id: SETTING_IDS.chatAgentMcpTools,
    label: "Chat Agent MCP tools",
    description: "Choose which n8n workflows and MCP tools Chat Agent can use",
    keywords: [
      "mcp",
      "chat agent",
      "tools",
      "workflow",
      "workflows",
      "n8n",
      "select",
    ],
    sectionId: SECTION_IDS.toolsMcp,
    sectionLabel: "Tools (MCP)",
  },
  {
    id: SETTING_IDS.chatAgentMcpWorkflows,
    label: "Chat Agent n8n workflows",
    description: "Choose which discovered n8n workflows Chat Agent may execute",
    keywords: [
      "mcp",
      "chat agent",
      "workflow",
      "workflows",
      "n8n",
      "execute",
      "select",
    ],
    sectionId: SECTION_IDS.toolsMcp,
    sectionLabel: "Tools (MCP)",
  },

  // Experiments
  {
    id: SETTING_IDS.nativeGit,
    label: "Enable Native Git",
    description:
      "Use native Git for faster performance without external installation",
    keywords: ["git", "native", "experiment", "beta", "performance"],
    sectionId: SECTION_IDS.experiments,
    sectionLabel: "Experiments",
  },
  {
    id: SETTING_IDS.enableCloudSandbox,
    label: "Enable Cloud Sandbox (Pro)",
    description:
      "Run your app on the Cloud for a more secure runtime that uses fewer local system resources",
    keywords: [
      "cloud",
      "sandbox",
      "runtime",
      "experiment",
      "pro",
      "credits",
      "secure",
    ],
    sectionId: SECTION_IDS.experiments,
    sectionLabel: "Experiments",
  },
  {
    id: SETTING_IDS.enableSandboxScriptExecution,
    label: "Enable sandbox script execution",
    description:
      "Allow local-agent attachment scripts to inspect files with execute_sandbox_script",
    keywords: [
      "script",
      "scripts",
      "sandbox",
      "attachments",
      "mustard",
      "agent",
      "experiment",
    ],
    sectionId: SECTION_IDS.experiments,
    sectionLabel: "Experiments",
  },
  {
    id: SETTING_IDS.blockUnsafeNpmPackages,
    label: "Block unsafe npm packages",
    description: "Uses socket.dev to detect unsafe packages and blocks them",
    keywords: ["socket", "npm", "firewall", "package", "unsafe", "security"],
    sectionId: SECTION_IDS.experiments,
    sectionLabel: "Experiments",
  },

  {
    id: SETTING_IDS.enableMcpServersForBuildMode,
    label: "Enable MCP servers for Build mode",
    description: "Allow MCP servers to be used when in Build mode",
    keywords: ["mcp", "build", "agent", "tools", "experiment", "server"],
    sectionId: SECTION_IDS.experiments,
    sectionLabel: "Experiments",
  },
  {
    id: SETTING_IDS.enableSelectAppFromHomeChatInput,
    label: "Enable Select App from Home Chat Input",
    description:
      "Show an app selector in the home chat input to start a chat referencing an existing app",
    keywords: ["app", "select", "home", "chat", "experiment", "input"],
    sectionId: SECTION_IDS.experiments,
    sectionLabel: "Experiments",
  },

  // Danger Zone
  {
    id: SETTING_IDS.reset,
    label: "Reset Everything",
    description:
      "Delete all apps, chats, and settings. This action cannot be undone.",
    keywords: ["reset", "delete", "clear", "wipe", "danger", "destructive"],
    sectionId: SECTION_IDS.dangerZone,
    sectionLabel: "Danger Zone",
  },
];
