CREATE TABLE `package_manifests` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`version` text NOT NULL,
	`description` text,
	`manifest_cid` text,
	`root_cid` text,
	`metadata_cid` text,
	`preview_cid` text,
	`policy_cid` text,
	`dataset_id` text,
	`chunk_count` integer DEFAULT 0 NOT NULL,
	`total_bytes` integer DEFAULT 0 NOT NULL,
	`chunk_cids` text,
	`merkle_root` text,
	`integrity_hashes` text,
	`provenance_json` text,
	`publisher_wallet` text,
	`publisher_signature` text,
	`signed_at` integer,
	`encrypted` integer DEFAULT true NOT NULL,
	`encryption_algorithm` text DEFAULT 'aes-256-gcm',
	`status` text DEFAULT 'draft' NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `policy_documents` (
	`id` text PRIMARY KEY NOT NULL,
	`manifest_id` text NOT NULL,
	`policy_cid` text,
	`license_tiers` text NOT NULL,
	`allowed_uses` text,
	`restrictions` text,
	`pricing_model` text DEFAULT 'free' NOT NULL,
	`price_amount` integer,
	`price_currency` text,
	`btc_taproot_address` text,
	`sovereign_exit_enabled` integer DEFAULT false NOT NULL,
	`privacy_statement` text DEFAULT 'Raw data not shared; encrypted payload only' NOT NULL,
	`raw_data_shared` integer DEFAULT false NOT NULL,
	`publisher_wallet` text,
	`publisher_signature` text,
	`signed_at` integer,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`manifest_id`) REFERENCES `package_manifests`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `publish_bundles` (
	`id` text PRIMARY KEY NOT NULL,
	`manifest_id` text NOT NULL,
	`policy_id` text NOT NULL,
	`manifest_cid` text NOT NULL,
	`policy_cid` text NOT NULL,
	`preview_cid` text,
	`listing_name` text NOT NULL,
	`listing_description` text,
	`listing_category` text,
	`listing_tags` text,
	`listing_preview_url` text,
	`listing_license` text,
	`listing_pricing_model` text,
	`listing_price` integer,
	`listing_currency` text,
	`thirdweb_listing_id` text,
	`polygon_contract_address` text,
	`marketplace_asset_id` text,
	`publisher_wallet` text NOT NULL,
	`publisher_signature` text NOT NULL,
	`status` text DEFAULT 'draft' NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL,
	FOREIGN KEY (`manifest_id`) REFERENCES `package_manifests`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`policy_id`) REFERENCES `policy_documents`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `transform_jobs` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`input_asset_ids` text NOT NULL,
	`input_dataset_id` text,
	`stages_json` text NOT NULL,
	`current_stage` text,
	`status` text DEFAULT 'pending' NOT NULL,
	`progress` integer DEFAULT 0 NOT NULL,
	`items_processed` integer DEFAULT 0 NOT NULL,
	`items_total` integer DEFAULT 0 NOT NULL,
	`output_asset_ids` text DEFAULT '[]' NOT NULL,
	`output_dataset_id` text,
	`error_message` text,
	`error_count` integer DEFAULT 0 NOT NULL,
	`audit_log_json` text DEFAULT '[]' NOT NULL,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`started_at` integer,
	`completed_at` integer
);
--> statement-breakpoint
CREATE TABLE `vault_assets` (
	`id` text PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`modality` text NOT NULL,
	`mime_type` text NOT NULL,
	`status` text DEFAULT 'ingested' NOT NULL,
	`content_hash` text NOT NULL,
	`byte_size` integer NOT NULL,
	`storage_path` text NOT NULL,
	`encrypted` integer DEFAULT false NOT NULL,
	`encryption_key_id` text,
	`connector_id` text,
	`connector_type` text,
	`source_path` text,
	`source_url` text,
	`tags` text DEFAULT '[]' NOT NULL,
	`collections` text DEFAULT '[]' NOT NULL,
	`quality_score` integer,
	`metadata_json` text,
	`pii_detected` integer DEFAULT false NOT NULL,
	`pii_redacted` integer DEFAULT false NOT NULL,
	`pii_fields_json` text,
	`imported_at` integer DEFAULT (unixepoch()) NOT NULL,
	`processed_at` integer,
	`published_at` integer,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `vault_audit_log` (
	`id` text PRIMARY KEY NOT NULL,
	`action` text NOT NULL,
	`target_id` text,
	`target_type` text,
	`details` text,
	`metadata_json` text,
	`timestamp` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `vault_connectors` (
	`id` text PRIMARY KEY NOT NULL,
	`type` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`status` text DEFAULT 'disabled' NOT NULL,
	`source_path` text,
	`source_url` text,
	`watch_pattern` text,
	`auto_import` integer DEFAULT false NOT NULL,
	`require_preview` integer DEFAULT true NOT NULL,
	`allowed_mime_types` text,
	`max_file_size` integer,
	`exclude_patterns` text,
	`sync_interval_minutes` integer,
	`last_sync_at` integer,
	`next_sync_at` integer,
	`total_imported` integer DEFAULT 0 NOT NULL,
	`total_bytes` integer DEFAULT 0 NOT NULL,
	`error_count` integer DEFAULT 0 NOT NULL,
	`last_error` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL,
	`updated_at` integer DEFAULT (unixepoch()) NOT NULL
);
