CREATE TABLE `openclaw_activity_log` (
	`id` text PRIMARY KEY NOT NULL,
	`event_type` text NOT NULL,
	`channel` text,
	`channel_message_id` text,
	`actor` text DEFAULT 'openclaw' NOT NULL,
	`actor_display_name` text,
	`content` text,
	`content_type` text DEFAULT 'text',
	`provider` text,
	`model` text,
	`agent_id` text,
	`task_id` text,
	`workflow_id` text,
	`tokens_used` integer,
	`duration_ms` integer,
	`local_processed` integer DEFAULT 0,
	`direction` text DEFAULT 'internal',
	`metadata_json` text,
	`external_event_id` text,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL
);
--> statement-breakpoint
CREATE TABLE `openclaw_channel_messages` (
	`id` text PRIMARY KEY NOT NULL,
	`channel` text NOT NULL,
	`channel_message_id` text,
	`channel_id` text,
	`channel_name` text,
	`sender_id` text NOT NULL,
	`sender_name` text NOT NULL,
	`sender_avatar` text,
	`is_bot` integer DEFAULT 0,
	`content` text NOT NULL,
	`content_type` text DEFAULT 'text',
	`attachments_json` text,
	`reply_to_message_id` text,
	`reply_to_content` text,
	`bot_response_id` text,
	`provider` text,
	`model` text,
	`tokens_used` integer,
	`duration_ms` integer,
	`platform_timestamp` integer,
	`created_at` integer DEFAULT (unixepoch()) NOT NULL
);
