export const MAX_CHAT_TURNS_IN_CONTEXT = 3;
export const DEFAULT_MAX_TOOL_CALL_STEPS = 100;
export const DEFAULT_SANDBOX_SCRIPT_TIMEOUT_MS = 2_000;
export const MAX_SANDBOX_SCRIPT_TIMEOUT_MS = 10_000;
