import fs from "fs";
import os from "os";
import path from "path";
import * as tar from "tar";
import { eq } from "drizzle-orm";
import log from "electron-log";

import { db } from "../../db";
import { apps, chats } from "../../db/schema";
import { getDyadAppPath, isAppLocationAccessible } from "../../paths/paths";
import { gitAdd, gitCommit, gitInit } from "./git_utils";
import {
  getBlobBuffer,
  isBlobConnected,
  listBlobs,
  uploadToBlob,
} from "./vercel_blob";

const logger = log.scope("app_cloud_backup");

// Directories never worth backing up — they're regenerated by install/build.
const EXCLUDE_DIRS = new Set([
  "node_modules",
  ".git",
  "dist",
  "build",
  ".next",
  ".vite",
  "out",
  ".turbo",
  ".cache",
  ".vercel",
]);

function tarFilter(entry: string): boolean {
  const segments = entry.replace(/^\.\//, "").split("/");
  return !segments.some((s) => EXCLUDE_DIRS.has(s));
}

/** Blob-safe file stem for an app name. */
function safeName(name: string): string {
  return name.trim().replace(/[^a-zA-Z0-9._-]+/g, "-") || "app";
}

export type CloudApp = {
  name: string;
  pathname: string;
  url: string;
  size: number;
  uploadedAt: string;
};

// Coalesce concurrent backups of the same app (auto-backup fires per commit).
const inFlight = new Set<number>();

/**
 * Tar the app's source (sans node_modules/.git/build output) and upload it to
 * the cloud `code/` folder. Best-effort: never throws to the caller.
 */
export async function backupAppSource(appId: number): Promise<void> {
  if (!isBlobConnected() || inFlight.has(appId)) return;
  inFlight.add(appId);
  let tmpFile: string | undefined;
  try {
    const app = await db.query.apps.findFirst({ where: eq(apps.id, appId) });
    if (!app) return;
    const appPath = getDyadAppPath(app.path);
    if (!fs.existsSync(appPath)) return;

    tmpFile = path.join(os.tmpdir(), `mh-code-${appId}-${Date.now()}.tgz`);
    await tar.create(
      {
        gzip: true,
        file: tmpFile,
        cwd: appPath,
        portable: true,
        filter: tarFilter,
      },
      ["."],
    );
    const buffer = await fs.promises.readFile(tmpFile);
    const pathname = `code/${safeName(app.name)}.tgz`;
    await uploadToBlob(pathname, buffer, {
      contentType: "application/gzip",
      allowOverwrite: true,
    });
    logger.log(
      `Backed up "${app.name}" source to ${pathname} (${buffer.length} bytes)`,
    );
  } catch (e) {
    logger.error(`Cloud backup failed for app ${appId}:`, e);
  } finally {
    inFlight.delete(appId);
    if (tmpFile) {
      try {
        await fs.promises.unlink(tmpFile);
      } catch {
        // temp file already gone — ignore
      }
    }
  }
}

/** List the source backups stored under the cloud `code/` folder. */
export async function listCloudApps(): Promise<CloudApp[]> {
  if (!isBlobConnected()) return [];
  const blobs = await listBlobs("code/");
  return blobs
    .filter((b) => b.pathname.endsWith(".tgz"))
    .map((b) => ({
      name: b.pathname.replace(/^code\//, "").replace(/\.tgz$/, ""),
      pathname: b.pathname,
      url: b.url,
      size: b.size,
      uploadedAt: b.uploadedAt,
    }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

async function uniqueAppName(base: string): Promise<string> {
  let candidate = base;
  let n = 1;
  while (
    (await db.query.apps.findFirst({ where: eq(apps.name, candidate) })) ||
    fs.existsSync(getDyadAppPath(candidate))
  ) {
    candidate = `${base} (${++n})`;
  }
  return candidate;
}

/**
 * Download a `code/` backup, extract it into a fresh local app, register it in
 * the database and return the new app id so the IDE can open it.
 */
export async function restoreAppFromCloud(input: {
  url: string;
  pathname: string;
}): Promise<{ appId: number; name: string }> {
  if (!isBlobConnected()) throw new Error("Vercel Blob is not connected.");
  const buffer = await getBlobBuffer(input.url);
  if (!buffer) throw new Error("Could not download the cloud backup.");

  const base =
    input.pathname.replace(/^code\//, "").replace(/\.tgz$/, "") ||
    "restored-app";
  const name = await uniqueAppName(base);
  const fullAppPath = getDyadAppPath(name);
  if (!isAppLocationAccessible(fullAppPath)) {
    throw new Error(
      "The apps folder is inaccessible. Check your custom apps folder setting.",
    );
  }

  await fs.promises.mkdir(fullAppPath, { recursive: true });
  const tmpFile = path.join(os.tmpdir(), `mh-restore-${Date.now()}.tgz`);
  try {
    await fs.promises.writeFile(tmpFile, buffer);
    await tar.extract({ file: tmpFile, cwd: fullAppPath });
  } finally {
    try {
      await fs.promises.unlink(tmpFile);
    } catch {
      // ignore
    }
  }

  await gitInit({ path: fullAppPath, ref: "main" });
  await gitAdd({ path: fullAppPath, filepath: "." });
  let commitHash: string | undefined;
  try {
    commitHash = await gitCommit({
      path: fullAppPath,
      message: "Restore from cloud",
    });
  } catch (e) {
    logger.error("Failed to commit restored app:", e);
  }

  const [app] = await db.insert(apps).values({ name, path: name }).returning();
  const [chat] = await db.insert(chats).values({ appId: app.id }).returning();
  if (commitHash) {
    await db
      .update(chats)
      .set({ initialCommitHash: commitHash })
      .where(eq(chats.id, chat.id));
  }

  logger.log(`Restored app "${name}" (id ${app.id}) from ${input.pathname}`);
  return { appId: app.id, name };
}
