/**
 * Post-processor that fixes broken `@shadcn/ui` imports generated by AI models.
 *
 * AI models often output `import { Button } from '@shadcn/ui'` which doesn't exist.
 * The correct pattern is `import { Button } from '@/components/ui/button'`.
 *
 * This runs on file content before it's written to disk, as a safety net
 * in case the model ignores the prompt rules.
 */

/** Convert PascalCase to kebab-case: "DropdownMenu" → "dropdown-menu" */
function pascalToKebab(name: string): string {
  return name
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/([A-Z])([A-Z][a-z])/g, "$1-$2")
    .toLowerCase();
}

/**
 * Known shadcn/ui component file basenames (PascalCase).
 * Sorted longest-first so "AlertDialog" matches before "Alert".
 */
const COMPONENT_BASES = [
  "NavigationMenu",
  "DropdownMenu",
  "ContextMenu",
  "AlertDialog",
  "AspectRatio",
  "RadioGroup",
  "ToggleGroup",
  "ScrollArea",
  "HoverCard",
  "InputOTP",
  "Breadcrumb",
  "Accordion",
  "Collapsible",
  "Resizable",
  "Pagination",
  "Carousel",
  "Menubar",
  "Command",
  "Popover",
  "Sidebar",
  "Tooltip",
  "Drawer",
  "Dialog",
  "Select",
  "Sheet",
  "Table",
  "Tabs",
  "Card",
  "Form",
  "Toast",
];

/**
 * Find the base component file for an imported name.
 * e.g. "CardHeader" → "card", "DropdownMenuItem" → "dropdown-menu", "Button" → "button"
 */
function resolveComponentFile(name: string): string {
  for (const base of COMPONENT_BASES) {
    if (name.startsWith(base)) {
      return pascalToKebab(base);
    }
  }
  // Default: convert the full name to kebab-case
  return pascalToKebab(name);
}

const SHADCN_IMPORT_RE =
  /import\s*\{([^}]+)\}\s*from\s*['"]@shadcn\/ui['"]/g;

/**
 * Fix `@shadcn/ui` imports in file content.
 * Only processes .ts/.tsx/.js/.jsx files (determined by filePath extension).
 *
 * Transforms:
 *   import { Button, Card, CardHeader } from '@shadcn/ui'
 * Into:
 *   import { Button } from '@/components/ui/button'
 *   import { Card, CardHeader } from '@/components/ui/card'
 */
export function fixShadcnImports(
  content: string,
  filePath: string,
): string {
  // Only process JS/TS files
  if (!/\.[jt]sx?$/.test(filePath)) return content;

  // Quick check before running regex
  if (!content.includes("@shadcn/ui")) return content;

  return content.replace(SHADCN_IMPORT_RE, (_match, importsRaw: string) => {
    const names = importsRaw
      .split(",")
      .map((s) => s.trim())
      .filter(Boolean);

    // Group names by their target file
    const groups = new Map<string, string[]>();
    for (const name of names) {
      const file = resolveComponentFile(name);
      if (!groups.has(file)) groups.set(file, []);
      groups.get(file)!.push(name);
    }

    return Array.from(groups.entries())
      .map(
        ([file, componentNames]) =>
          `import { ${componentNames.join(", ")} } from '@/components/ui/${file}'`,
      )
      .join("\n");
  });
}
