export const GIT_ERROR_CODES = {
  MERGE_IN_PROGRESS: "MERGE_IN_PROGRESS",
  REBASE_IN_PROGRESS: "REBASE_IN_PROGRESS",
  MERGE_CONFLICT: "MERGE_CONFLICT",
  PRE_COMMIT_FAILED: "PRE_COMMIT_FAILED",
  NON_FAST_FORWARD: "NON_FAST_FORWARD",
  DIVERGENT_BRANCHES: "DIVERGENT_BRANCHES",
  UNCOMMITTED_CHANGES: "UNCOMMITTED_CHANGES",
} as const;

export type GitErrorCode =
  (typeof GIT_ERROR_CODES)[keyof typeof GIT_ERROR_CODES];
