name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main, cursor/create-stealthy-multi-layered-code-e0db ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: 'dyad-ai-app'
          directory: '.'
          # Optional: git commit hash to deploy (default is HEAD)
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Wrangler version, defaults to latest
          wranglerVersion: '3'