// See the Electron documentation for details on how to use preload scripts:
// https://www.electronjs.org/docs/latest/tutorial/process-model#preload-scripts

import { contextBridge, ipcRenderer, webFrame } from "electron";

// Whitelist of valid channels
const validInvokeChannels = [
  "analyze-component",
  "apply-visual-editing-changes",
  "get-language-models",
  "get-language-models-by-providers",
  "create-custom-language-model",
  "get-language-model-providers",
  "delete-custom-language-model-provider",
  "create-custom-language-model-provider",
  "edit-custom-language-model-provider",
  "delete-custom-language-model",
  "delete-custom-model",
  "chat:add-dep",
  "chat:message",
  "chat:cancel",
  "chat:stream",
  "chat:count-tokens",
  "create-chat",
  "create-app",
  "copy-app",
  "get-chat",
  "get-chats",
  "search-chats",
  "get-chat-logs",
  "list-apps",
  "get-app",
  "get-app-env-vars",
  "set-app-env-vars",
  "edit-app-file",
  "read-app-file",
  "run-app",
  "stop-app",
  "restart-app",
  "respond-to-app-input",
  "search-app",
  "list-versions",
  "revert-version",
  "checkout-version",
  "get-current-branch",
  "delete-app",
  "rename-app",
  "get-user-settings",
  "set-user-settings",
  "get-env-vars",
  "open-external-url",
  "show-item-in-folder",
  "reset-all",
  "nodejs-status",
  "install-node",
  "select-node-folder",
  "github:start-flow",
  "github:list-repos",
  "github:get-repo-branches",
  "github:is-repo-available",
  "github:create-repo",
  "github:connect-existing-repo",
  "github:push",
  "github:disconnect",
  "neon:create-project",
  "neon:get-project",
  "neon:delete-branch",
  "vercel:save-token",
  "vercel:list-projects",
  "vercel:is-project-available",
  "vercel:create-project",
  "vercel:connect-existing-project",
  "vercel:get-deployments",
  "vercel:disconnect",
  "get-app-version",
  "reload-env-path",
  "get-proposal",
  "approve-proposal",
  "reject-proposal",
  "get-system-debug-info",
  "supabase:list-organizations",
  "supabase:delete-organization",
  "supabase:list-all-projects",
  "supabase:list-branches",
  "supabase:get-edge-logs",
  "supabase:set-app-project",
  "supabase:unset-app-project",
  "local-models:list-ollama",
  "local-models:list-lmstudio",
  "window:minimize",
  "window:maximize",
  "window:close",
  "get-system-platform",
  "upload-to-signed-url",
  "delete-chat",
  "update-chat",
  "delete-messages",
  "start-chat-stream",
  "does-release-note-exist",
  "import-app",
  "check-ai-rules",
  "select-app-folder",
  "check-app-name",
  "rename-branch",
  "clear-session-data",
  "get-user-budget",
  "get-context-paths",
  "set-context-paths",
  "get-app-upgrades",
  "execute-app-upgrade",
  "is-capacitor",
  "sync-capacitor",
  "open-ios",
  "open-android",
  "check-problems",
  "restart-joy",
  "get-templates",
  "portal:migrate-create",
  // Voice Assistant
  "voice:initialize",
  "voice:shutdown",
  "voice:get-config",
  "voice:update-config",
  "voice:get-state",
  "voice:start-listening",
  "voice:stop-listening",
  "voice:transcribe-file",
  "voice:speak",
  "voice:download-whisper-model",
  "voice:get-installed-models",
  "voice:subscribe",
  // Memory System (Persistent AI Memory)
  "memory:initialize",
  "memory:shutdown",
  "memory:create",
  "memory:get",
  "memory:update",
  "memory:delete",
  "memory:search",
  "memory:fulltext-search",
  "memory:get-context",
  "memory:add-to-context",
  "memory:clear-context",
  "memory:get-profile",
  "memory:update-profile",
  "memory:learn-preference",
  "memory:create-relationship",
  "memory:get-related",
  "memory:consolidate",
  "memory:stats",
  "memory:subscribe",
  // Plugin System (Plugin Marketplace)
  "plugin:initialize",
  "plugin:shutdown",
  "plugin:list",
  "plugin:get",
  "plugin:is-enabled",
  "plugin:install-from-registry",
  "plugin:install-from-url",
  "plugin:install-from-file",
  "plugin:uninstall",
  "plugin:update",
  "plugin:enable",
  "plugin:disable",
  "plugin:get-config",
  "plugin:set-config",
  "plugin:grant-permission",
  "plugin:revoke-permission",
  "plugin:search-registry",
  "plugin:get-registry-plugin",
  "plugin:subscribe",
  // Model Benchmark System
  "benchmark:initialize",
  "benchmark:shutdown",
  "benchmark:run",
  "benchmark:cancel",
  "benchmark:get",
  "benchmark:list",
  "benchmark:delete",
  "benchmark:get-datasets",
  "benchmark:subscribe",
  // AI Coding Agent
  "coding-agent:create-session",
  "coding-agent:end-session",
  "coding-agent:get-session",
  "coding-agent:list-sessions",
  "coding-agent:run-task",
  "coding-agent:approve-action",
  "coding-agent:get-pending-approvals",
  "coding-agent:get-capabilities",
  "coding-agent:subscribe",
  "coding-agent:unsubscribe",
  // Design System Generator
  "design-system:initialize",
  "design-system:create",
  "design-system:generate",
  "design-system:get",
  "design-system:list",
  "design-system:delete",
  "design-system:update-tokens",
  "design-system:generate-component",
  "design-system:update-component",
  "design-system:delete-component",
  "design-system:export",
  "design-system:subscribe",
  "design-system:unsubscribe",
  // Secrets Vault
  "secrets-vault:initialize",
  "secrets-vault:check-exists",
  "secrets-vault:create",
  "secrets-vault:unlock",
  "secrets-vault:lock",
  "secrets-vault:delete",
  "secrets-vault:change-password",
  "secrets-vault:get-status",
  "secrets-vault:set-auto-lock",
  "secrets-vault:create-secret",
  "secrets-vault:get-secret",
  "secrets-vault:update-secret",
  "secrets-vault:delete-secret",
  "secrets-vault:list-secrets",
  "secrets-vault:get-stats",
  "secrets-vault:create-backup",
  "secrets-vault:restore-backup",
  "secrets-vault:list-backups",
  "secrets-vault:delete-backup",
  "secrets-vault:subscribe",
  "secrets-vault:unsubscribe",
  // Offline Docs Hub
  "offline-docs:initialize",
  "offline-docs:shutdown",
  "offline-docs:get-bundled",
  "offline-docs:create-collection",
  "offline-docs:get-collection",
  "offline-docs:list-collections",
  "offline-docs:update-collection",
  "offline-docs:delete-collection",
  "offline-docs:get-document",
  "offline-docs:list-documents",
  "offline-docs:delete-document",
  "offline-docs:search",
  "offline-docs:import-folder",
  "offline-docs:import-url",
  "offline-docs:get-import-progress",
  "offline-docs:get-stats",
  "offline-docs:subscribe",
  "offline-docs:unsubscribe",
  // MCP
  "mcp:list-servers",
  "mcp:create-server",
  "mcp:update-server",
  "mcp:delete-server",
  "mcp:list-tools",
  "mcp:get-tool-consents",
  "mcp:set-tool-consent",
  // MCP consent response from renderer to main
  "mcp:tool-consent-response",
  // Agent Tools (Local Agent v2)
  "agent-tool:get-tools",
  "agent-tool:set-consent",
  "agent-tool:consent-response",
  // Help
  "take-screenshot",
  // Help bot
  "help:chat:start",
  "help:chat:cancel",
  // Prompts
  "prompts:list",
  "prompts:create",
  "prompts:update",
  "prompts:delete",
  // adding app to favorite
  "add-to-favorite",
  "github:clone-repo-from-url",
  "get-latest-security-review",
  // Agent Builder
  "agent:create",
  "agent:get",
  "agent:list",
  "agent:update",
  "agent:delete",
  "agent:duplicate",
  "agent:tool:create",
  "agent:tool:list",
  "agent:tool:update",
  "agent:tool:delete",
  "agent:workflow:create",
  "agent:workflow:list",
  "agent:workflow:update",
  "agent:workflow:delete",
  "agent:deploy",
  "agent:deployment:list",
  "agent:deployment:stop",
  "agent:test:create",
  "agent:test:list",
  "agent:kb:create",
  "agent:kb:list",
  "agent:ui:create",
  "agent:ui:list",
  "agent:export:json",
  "agent:export:standalone",
  "agent:export:docker",
  // n8n Integration
  "n8n:start",
  "n8n:stop",
  "n8n:status",
  "n8n:db:configure",
  "n8n:db:get-config",
  "n8n:workflow:create",
  "n8n:workflow:update",
  "n8n:workflow:get",
  "n8n:workflow:list",
  "n8n:workflow:delete",
  "n8n:workflow:activate",
  "n8n:workflow:deactivate",
  "n8n:workflow:execute",
  "n8n:workflow:generate",
  "n8n:meta-builder:create",
  "n8n:agent:send-message",
  "n8n:agent:get-messages",
  "n8n:agent:create-collaboration",
  "n8n:agent:get-collaboration",
  "n8n:agent:list-collaborations",
  "n8n:agent:create-collab-workflow",
  // Trustless Local Inference
  "trustless:initialize",
  "trustless:shutdown",
  "trustless:check-providers",
  "trustless:list-models",
  "trustless:get-model-info",
  "trustless:run-inference",
  "trustless:start-stream",
  "trustless:verify-record",
  "trustless:get-record",
  "trustless:list-records",
  "trustless:export-proof",
  "trustless:import-proof",
  "trustless:pin-record",
  "trustless:unpin-record",
  "trustless:create-batch-proof",
  "trustless:verify-batch-proof",
  "trustless:helia-status",
  "trustless:get-stats",
  // IPLD Receipts
  "receipt:create",
  "receipt:list",
  "receipt:get",
  "receipt:verify",
  // LibreOffice Integration
  "libreoffice:status",
  "libreoffice:create",
  "libreoffice:list",
  "libreoffice:get",
  "libreoffice:delete",
  "libreoffice:export",
  "libreoffice:open",
  "libreoffice:download",
  "libreoffice:show-in-folder",
  "libreoffice:get-directory",
  // Marketplace Integration
  "marketplace:status",
  "marketplace:connect",
  "marketplace:disconnect",
  "marketplace:get-profile",
  "marketplace:list-assets",
  "marketplace:get-asset",
  "marketplace:publish",
  "marketplace:update-asset",
  "marketplace:unpublish",
  "marketplace:earnings",
  "marketplace:export-zip",
  "marketplace:deployment-status",
  "marketplace:open",
  "marketplace:get-url",
  // JoyMarketplace.io Sync (Local → Online)
  "marketplace-sync:get-config",
  "marketplace-sync:connect",
  "marketplace-sync:disconnect",
  "marketplace-sync:get-store-from-domain",
  "marketplace-sync:verify-domain",
  "marketplace-sync:set-default-store",
  "marketplace-sync:get-default-store",
  "marketplace-sync:sync-listing",
  "marketplace-sync:batch-sync",
  "marketplace-sync:ingest-receipt",
  "marketplace-sync:verify-receipt",
  "marketplace-sync:configure-pinning",
  "marketplace-sync:pin-receipt",
  "marketplace-sync:pin-receipts-batch",
  "marketplace-sync:get-pin-status",
  "marketplace-sync:unpin-receipt",
  "marketplace-sync:get-gateway-url",
  "marketplace-sync:verify-payout",
  "marketplace-sync:get-usdc-balance",
  "marketplace-sync:get-nft-metadata",
  "marketplace-sync:get-owned-nfts",
  // Web Scraper & Dataset Management
  "scraper:status",
  "scraper:config:list",
  "scraper:config:save",
  "scraper:config:delete",
  "scraper:templates",
  "scraper:job:start",
  "scraper:job:status",
  "scraper:job:list",
  "scraper:job:cancel",
  "scraper:dataset:list",
  "scraper:dataset:get",
  "scraper:dataset:preview",
  "scraper:dataset:export",
  "scraper:dataset:delete",
  "scraper:dataset:create",
  "scraper:dataset:import",
  "scraper:quick-scrape",
  // Asset Studio
  "assets:stats",
  "assets:list",
  "assets:list-all",
  "assets:get",
  "assets:delete",
  "assets:update",
  "assets:export",
  "assets:import",
  "assets:open-folder",
  "assets:read-file",
  "assets:create:algorithm",
  "assets:create:schema",
  "assets:create:prompt",
  "assets:create:ui-component",
  "assets:create:api",
  "assets:create:training-data",
  "assets:get-directory",
  // Dataset Studio (Multimodal Dataset Creation with Provenance)
  "dataset-studio:create-dataset",
  "dataset-studio:list-datasets",
  "dataset-studio:get-dataset",
  "dataset-studio:update-dataset",
  "dataset-studio:delete-dataset",
  "dataset-studio:refresh-stats",
  "dataset-studio:add-item-from-file",
  "dataset-studio:add-generated-item",
  "dataset-studio:update-item-labels",
  "dataset-studio:update-quality-signals",
  "dataset-studio:list-items",
  "dataset-studio:get-item",
  "dataset-studio:delete-item",
  "dataset-studio:build-manifest",
  "dataset-studio:create-splits",
  "dataset-studio:sign-manifest",
  "dataset-studio:get-manifest",
  "dataset-studio:create-generation-job",
  "dataset-studio:get-job-status",
  "dataset-studio:list-jobs",
  "dataset-studio:init-p2p-sync",
  "dataset-studio:get-p2p-sync-status",
  "dataset-studio:get-content",
  "dataset-studio:export-dataset",
  // NFT Marketplace
  "nft:chunk-asset",
  "nft:get-chunks",
  "nft:create-listing",
  "nft:bulk-create-listings",
  "nft:list-all",
  "nft:list-by-asset",
  "nft:get-listing",
  "nft:update-pricing",
  "nft:update-status",
  "nft:publish",
  "nft:bulk-publish",
  "nft:delete-listing",
  "nft:portfolio",
  "nft:stats",
  // Federation & P2P Marketplace
  "federation:create-identity",
  "federation:get-identity",
  "federation:get-peers",
  "federation:get-connected-peers",
  "federation:connect-peer",
  "federation:disconnect-peer",
  "federation:add-peer",
  "federation:bootstrap:list",
  "federation:bootstrap:add",
  "federation:bootstrap:remove",
  "federation:bootstrap:import",
  "federation:dht-put",
  "federation:dht-get",
  "federation:model-chunk-serve",
  "federation:model-chunk-request",
  "federation:model-chunk-announce",
  "federation:model-chunk-find",
  "federation:route-inference",
  "federation:execute-inference",
  "federation:execute-inference-stream",
  "federation:model-chunk-listing:create",
  "federation:model-chunk-listing:list",
  "federation:model-chunk-purchase:create",
  "federation:model-chunk-purchase:list",
  "federation:model-chunk-escrow:create",
  "federation:create-listing",
  "federation:get-listings",
  "federation:search-listings",
  "federation:initiate-transaction",
  "federation:update-transaction",
  "federation:get-transactions",
  "federation:create-escrow",
  "federation:send-message",
  "federation:get-conversations",
  "federation:get-stats",
  // Sovereign Data (Local-First Encrypted Storage)
  "sovereign:get-vault",
  "sovereign:update-vault-config",
  "sovereign:enable-network",
  "sovereign:store-data",
  "sovereign:retrieve-data",
  "sovereign:list-data",
  "sovereign:delete-data",
  "sovereign:sync-to-network",
  "sovereign:pin-to-ipfs",
  "sovereign:store-on-arweave",
  "sovereign:run-local-inference",
  "sovereign:share-data",
  "sovereign:revoke-access",
  "sovereign:update-consent",
  "sovereign:queue-sync",
  "sovereign:queue-share",
  "sovereign:list-outbox",
  "sovereign:process-outbox",
  "sovereign:policy-audit",
  "sovereign:create-listing",
  "sovereign:get-listings",
  "sovereign:get-purchases",
  "sovereign:record-purchase",
  "sovereign:export-data",
  "sovereign:import-data",
  // Decentralized Deployment (4everland, Fleek, IPFS, Arweave, etc.)
  "decentralized:save-credentials",
  "decentralized:get-credentials",
  "decentralized:remove-credentials",
  "decentralized:deploy",
  "decentralized:get-deployments",
  "decentralized:get-deployment",
  "decentralized:check-pin-status",
  "decentralized:get-platforms",
  // Project Management
  "project:create",
  "project:list",
  "project:get",
  "project:update",
  "project:delete",
  // Hybrid Bridge (Local/Cloud Integration)
  "hybrid-bridge:start",
  "hybrid-bridge:stop",
  "hybrid-bridge:status",
  "hybrid-bridge:config:update",
  "hybrid-bridge:config:get",
  "hybrid-bridge:service:add",
  "hybrid-bridge:service:remove",
  "hybrid-bridge:service:reconnect",
  "hybrid-bridge:service:list",
  "hybrid-bridge:sync:run",
  "hybrid-bridge:sync:state",
  "hybrid-bridge:sync:clear-errors",
  "hybrid-bridge:request",
  "hybrid-bridge:n8n:restart",
  "hybrid-bridge:n8n:health",
  // Decentralized Chat (Wallet-to-Wallet)
  "dchat:identity:create",
  "dchat:identity:get",
  "dchat:identity:update",
  "dchat:conversation:create",
  "dchat:conversation:get",
  "dchat:conversation:list",
  "dchat:conversation:get-direct",
  "dchat:message:send",
  "dchat:message:get",
  "dchat:message:decrypt",
  "dchat:pin:pull",
  "dchat:sync:online",
  "dchat:offline:check",
  "dchat:presence:broadcast",
  "dchat:typing:send",
  "dchat:status",
  "dchat:test:encryption",
  "dchat:test:pin",
  "dchat:test:connectivity",
  // Compute Network (Decentralized AI Inference)
  "compute-network:initialize",
  "compute-network:shutdown",
  "compute-network:get-status",
  "compute-network:get-config",
  "compute-network:update-config",
  "compute-network:get-peers",
  "compute-network:get-peer",
  "compute-network:get-connections",
  "compute-network:connect-peer",
  "compute-network:disconnect-peer",
  "compute-network:fetch-content",
  "compute-network:pin-content",
  "compute-network:unpin-content",
  "compute-network:store-content",
  "compute-network:get-fetch-progress",
  "compute-network:create-job",
  "compute-network:accept-job",
  "compute-network:cancel-job",
  "compute-network:get-jobs",
  "compute-network:get-job",
  "compute-network:get-active-jobs",
  "compute-network:get-pending-jobs",
  "compute-network:request-validation",
  "compute-network:get-validation-requests",
  "compute-network:get-job-stats",
  "compute-network:get-system-metrics",
  "compute-network:get-network-metrics",
  "compute-network:subscribe",
  // WebRTC (Decentralized P2P Communication)
  "webrtc:init",
  "webrtc:status",
  "webrtc:ice:list",
  "webrtc:ice:register",
  "webrtc:peer:connect",
  "webrtc:peer:disconnect",
  "webrtc:peer:list",
  "webrtc:data:send",
  "webrtc:signaling:receive",
  "webrtc:call:start",
  "webrtc:call:answer",
  "webrtc:call:end",
  "webrtc:call:mute",
  "webrtc:call:video",
  // JoyCreate Node (JCN) - Local Asset Publishing & Inference
  "jcn:auth:createToken",
  "jcn:auth:verifyToken",
  "jcn:auth:signMessage",
  "jcn:publish:asset",
  "jcn:publish:getStatus",
  "jcn:publish:list",
  "jcn:publish:retry",
  "jcn:job:submit",
  "jcn:job:getStatus",
  "jcn:job:list",
  "jcn:job:cancel",
  "jcn:bundle:build",
  "jcn:bundle:verify",
  "jcn:bundle:get",
  "jcn:bundle:list",
  "jcn:storage:pin",
  "jcn:storage:fetch",
  "jcn:storage:verify",
  "jcn:license:register",
  "jcn:license:verify",
  "jcn:license:list",
  "jcn:license:revoke",
  "jcn:key:generate",
  "jcn:key:import",
  "jcn:key:list",
  "jcn:key:delete",
  "jcn:key:sign",
  "jcn:key:verify",
  "jcn:key:rotate",
  "jcn:admin:auditLog",
  "jcn:admin:replay",
  "jcn:admin:recover",
  "jcn:admin:stats",
  "jcn:chain:pollPending",
  "jcn:chain:checkReorgs",
  // Smart Router (Intelligent Local/Cloud Routing)
  "smart-router:route",
  "smart-router:record-result",
  "smart-router:list-providers",
  "smart-router:get-provider",
  "smart-router:register-provider",
  "smart-router:update-provider-status",
  "smart-router:get-config",
  "smart-router:update-config",
  "smart-router:get-stats",
  // AI Learning Mode
  "ai-learning:initialize",
  "ai-learning:shutdown",
  "ai-learning:create-profile",
  "ai-learning:get-profile",
  "ai-learning:list-profiles",
  "ai-learning:update-profile",
  "ai-learning:delete-profile",
  "ai-learning:activate-profile",
  "ai-learning:get-active-profile",
  "ai-learning:learn-pattern",
  "ai-learning:get-pattern",
  "ai-learning:list-patterns",
  "ai-learning:update-pattern",
  "ai-learning:add-pattern-example",
  "ai-learning:delete-pattern",
  "ai-learning:search-patterns",
  "ai-learning:record-feedback",
  "ai-learning:list-feedback",
  "ai-learning:get-style-guide",
  "ai-learning:update-style-guide",
  "ai-learning:get-communication-prefs",
  "ai-learning:update-communication-prefs",
  "ai-learning:generate-context",
  "ai-learning:get-stats",
  "ai-learning:subscribe",
  "ai-learning:unsubscribe",
  // Agent Swarm System
  "agent-swarm:initialize",
  "agent-swarm:shutdown",
  "agent-swarm:create-swarm",
  "agent-swarm:get-swarm",
  "agent-swarm:list-swarms",
  "agent-swarm:update-swarm",
  "agent-swarm:start-swarm",
  "agent-swarm:pause-swarm",
  "agent-swarm:terminate-swarm",
  "agent-swarm:delete-swarm",
  "agent-swarm:spawn-agent",
  "agent-swarm:get-agent",
  "agent-swarm:list-agents",
  "agent-swarm:get-agent-children",
  "agent-swarm:get-agent-lineage",
  "agent-swarm:update-agent",
  "agent-swarm:start-agent",
  "agent-swarm:stop-agent",
  "agent-swarm:terminate-agent",
  "agent-swarm:replicate-agent",
  "agent-swarm:list-replications",
  "agent-swarm:start-witness",
  "agent-swarm:record-observation",
  "agent-swarm:add-witness-insight",
  "agent-swarm:end-witness",
  "agent-swarm:get-witness",
  "agent-swarm:list-witnesses",
  "agent-swarm:assign-task",
  "agent-swarm:delegate-task",
  "agent-swarm:complete-task",
  "agent-swarm:fail-task",
  "agent-swarm:send-message",
  "agent-swarm:acknowledge-message",
  "agent-swarm:list-messages",
  "agent-swarm:share-knowledge",
  "agent-swarm:apply-knowledge",
  "agent-swarm:rate-knowledge",
  "agent-swarm:search-knowledge",
  "agent-swarm:get-knowledge",
  "agent-swarm:list-knowledge",
  "agent-swarm:get-swarm-stats",
  "agent-swarm:get-agent-stats",
  "agent-swarm:get-recent-events",
  "agent-swarm:subscribe",
  "agent-swarm:unsubscribe",
  // Autonomous Agent System - Fully autonomous perpetually growing AI
  "autonomous-agent:initialize",
  "autonomous-agent:shutdown",
  "autonomous-agent:create-agent",
  "autonomous-agent:get-agent",
  "autonomous-agent:list-agents",
  "autonomous-agent:activate-agent",
  "autonomous-agent:terminate-agent",
  "autonomous-agent:replicate-agent",
  "autonomous-agent:get-agent-stats",
  "autonomous-agent:create-mission",
  "autonomous-agent:get-mission",
  "autonomous-agent:list-missions",
  "autonomous-agent:get-artifact",
  "autonomous-agent:list-artifacts",
  "autonomous-agent:transcribe-audio",
  "autonomous-agent:synthesize-speech",
  "autonomous-agent:get-events",
  "autonomous-agent:subscribe",
  "autonomous-agent:unsubscribe",
  "autonomous-agent:inference-response",
  // Autonomous Agent Production - Resource monitoring, security, scheduling, approvals, etc.
  "autonomous-prod:initialize",
  "autonomous-prod:shutdown",
  "autonomous-prod:get-resources",
  "autonomous-prod:get-throttle-state",
  "autonomous-prod:check-permission",
  "autonomous-prod:get-audit-log",
  "autonomous-prod:create-schedule",
  "autonomous-prod:get-schedules",
  "autonomous-prod:request-approval",
  "autonomous-prod:respond-approval",
  "autonomous-prod:get-pending-approvals",
  "autonomous-prod:get-templates",
  "autonomous-prod:get-template",
  "autonomous-prod:create-notification",
  "autonomous-prod:get-notifications",
  "autonomous-prod:mark-notification-read",
  "autonomous-prod:get-system-health",
  "autonomous-prod:check-quota",
  "autonomous-prod:record-quota-usage",
  "autonomous-prod:add-knowledge-node",
  "autonomous-prod:add-knowledge-edge",
  "autonomous-prod:query-knowledge",
  "autonomous-prod:record-event",
  "autonomous-prod:get-metrics",
  "autonomous-prod:create-backup",
  "autonomous-prod:list-backups",
  "autonomous-prod:subscribe",
  "autonomous-prod:unsubscribe",
  // Model Factory - LoRA/QLoRA training for low GPU systems
  "model-factory:get-system-info",
  "model-factory:create-job",
  "model-factory:start-training",
  "model-factory:cancel-training",
  "model-factory:get-job",
  "model-factory:list-jobs",
  "model-factory:export-model",
  "model-factory:import-adapter",
  "model-factory:list-adapters",
  "model-factory:delete-adapter",
  // Agent Factory - Custom AI agent creation and training
  "agent-factory:create",
  "agent-factory:get",
  "agent-factory:list",
  "agent-factory:update",
  "agent-factory:delete",
  "agent-factory:duplicate",
  "agent-factory:start-training",
  "agent-factory:training-status",
  "agent-factory:cancel-training",
  "agent-factory:add-skill",
  "agent-factory:remove-skill",
  "agent-factory:list-skills",
  "agent-factory:add-tool",
  "agent-factory:remove-tool",
  "agent-factory:list-tools",
  "agent-factory:test",
  "agent-factory:set-adapter",
  "agent-factory:list-templates",
  "agent-factory:create-from-template",
  "agent-factory:export",
  "agent-factory:import",
  // Privacy-Preserving Inference Bridge - Local-first AI
  "privacy-inference:initialize",
  "privacy-inference:get-state",
  "privacy-inference:update-config",
  "privacy-inference:get-config",
  "privacy-inference:infer",
  "privacy-inference:local-complete",
  "privacy-inference:agent-task",
  "privacy-inference:get-stats",
  "privacy-inference:reset-stats",
  "privacy-inference:register-adapter",
  "privacy-inference:register-agent",
  "privacy-inference:add-trusted-peer",
  "privacy-inference:remove-trusted-peer",
  "privacy-inference:get-privacy-profiles",
  "privacy-inference:get-routing-profiles",
  // Deployed Contracts & NFT-Gated Inference Access
  "contracts:configure",
  "contracts:fetch-deployed",
  "contracts:fetch-inference-nfts",
  "contracts:get-owned-nfts",
  "contracts:get-for-asset",
  "contracts:verify-access",
  "contracts:request-decryption-key",
  "contracts:deploy",
  "contracts:mint-access-nft",
  "contracts:record-usage",
  "contracts:get-audit-logs",
  // Data Sovereignty & Monetization
  "sovereignty:get-vault",
  "sovereignty:update-vault",
  "sovereignty:protect",
  "sovereignty:batch-protect",
  "sovereignty:get-asset",
  "sovereignty:list-assets",
  "sovereignty:delete-asset",
  "sovereignty:verify-access",
  "sovereignty:revoke-access",
  "sovereignty:grant-access",
  "sovereignty:update-monetization",
  "sovereignty:enable-monetization",
  "sovereignty:report-harvester",
  "sovereignty:get-blocklist",
  "sovereignty:update-anti-harvesting",
  "sovereignty:get-analytics",
  "sovereignty:get-access-logs",
  // Hyper Liquid Data Pipeline (Local → Marketplace)
  "hyper-liquid:get-pipelines",
  "hyper-liquid:get-pipeline",
  "hyper-liquid:create-pipeline",
  "hyper-liquid:update-pipeline",
  "hyper-liquid:delete-pipeline",
  "hyper-liquid:start-pipeline",
  "hyper-liquid:stop-pipeline",
  "hyper-liquid:pause-pipeline",
  "hyper-liquid:resume-pipeline",
  "hyper-liquid:start-flow",
  "hyper-liquid:batch-flow",
  "hyper-liquid:get-flow",
  "hyper-liquid:get-flows",
  "hyper-liquid:cancel-flow",
  "hyper-liquid:retry-flow",
  "hyper-liquid:get-queue",
  "hyper-liquid:get-queues",
  "hyper-liquid:get-stats",
  "hyper-liquid:reset-stats",
  "hyper-liquid:check-dedup",
  "hyper-liquid:get-checkpoint",
  "hyper-liquid:resume-from-checkpoint",
  "hyper-liquid:status",
  // OpenClaw Gateway - Local AI Gateway with n8n integration
  "openclaw:initialize",
  "openclaw:shutdown",
  "openclaw:gateway:start",
  "openclaw:gateway:stop",
  "openclaw:gateway:status",
  "openclaw:config:get",
  "openclaw:config:update",
  "openclaw:claude-code:config:get",
  "openclaw:claude-code:config:update",
  "openclaw:provider:list",
  "openclaw:provider:health",
  "openclaw:provider:configure",
  "openclaw:provider:remove",
  "openclaw:provider:set-api-key",
  "openclaw:chat",
  "openclaw:chat:stream",
  "openclaw:agent:execute-task",
  "openclaw:agent:execute-with-n8n",
  "openclaw:claude-code:execute",
  "openclaw:claude-code:batch",
  "openclaw:n8n:trigger-workflow",
  "openclaw:n8n:create-agent-workflow",
  "openclaw:autonomous:create-app",
  "openclaw:autonomous:refactor-code",
  "openclaw:autonomous:analyze-codebase",
  "openclaw:quick:generate-code",
  "openclaw:quick:explain-code",
  "openclaw:quick:fix-error",
  "openclaw:subscribe",
  "openclaw:unsubscribe",
  // OpenClaw Data Pipeline - Scraping, Data Collection & Image Generation
  "openclaw:data:initialize",
  "openclaw:data:scrape",
  "openclaw:data:scrape:single",
  "openclaw:data:image:generate",
  "openclaw:data:image:enhance-prompt",
  "openclaw:data:pipeline:run",
  "openclaw:data:request",
  "openclaw:data:jobs:list",
  "openclaw:data:jobs:get",
  "openclaw:data:jobs:cancel",
  "openclaw:data:events:subscribe",
  "openclaw:data:events:unsubscribe",
  // OpenClaw System Integration - Unified AI gateway across all systems
  "openclaw:system:initialize",
  "openclaw:system:config:get",
  "openclaw:system:config:update",
  "openclaw:system:stats",
  "openclaw:system:history",
  "openclaw:system:execute",
  "openclaw:system:chat",
  "openclaw:system:agent-inference",
  "openclaw:system:events:subscribe",
  // OpenClaw Local AI Hub Integration
  "openclaw:local-hub:status",
  "openclaw:local-hub:chat",
  "openclaw:local-hub:combined-stats",
  // Studio AI Service (Claude Code + Ollama Integration)
  "studio-ai:initialize",
  "studio-ai:config:get",
  "studio-ai:config:update",
  "studio-ai:stats",
  "studio-ai:execute",
  "studio-ai:data:generate-items",
  "studio-ai:data:augment",
  "studio-ai:data:analyze",
  "studio-ai:document:generate",
  "studio-ai:document:enhance",
  "studio-ai:asset:generate-code",
  "studio-ai:asset:generate-schema",
  "studio-ai:asset:analyze-code",
  "studio-ai:asset:refactor-code",
  "studio-ai:asset:generate-tests",
  "studio-ai:swarm:generate-agent-config",
  "studio-ai:swarm:execute-task",
  "studio-ai:swarm:coordinate",
  "studio-ai:swarm:optimize-agent",
  "studio-ai:dataset:generate-qa-pairs",
  "studio-ai:dataset:generate-conversations",
  "studio-ai:dataset:generate-classification-data",
  // 🦞 OpenClaw Personal AI Assistant Integration
  // Multi-channel messaging (WhatsApp, Telegram, Slack, Discord, Signal, iMessage, etc.)
  // AI agents with thinking levels, memory search, plugin management
  // EXFOLIATE! EXFOLIATE!
  "openclaw:gateway:health",
  "openclaw:gateway:restart",
  "openclaw:connection:status",
  "openclaw:agent:run",
  "openclaw:message:send",
  "openclaw:message:broadcast",
  "openclaw:message:read",
  "openclaw:memory:search",
  "openclaw:channels:list",
  "openclaw:channels:configure",
  "openclaw:plugins:list",
  "openclaw:plugins:install",
  "openclaw:plugins:uninstall",
  "openclaw:plugins:enable",
  "openclaw:plugins:disable",
  "openclaw:doctor",
  // 🦞 OpenClaw CNS (Central Nervous System) - Ollama & N8n Integration
  // Unified AI routing with local (Ollama) and cloud (Anthropic) backends
  "cns:initialize",
  "cns:shutdown",
  "cns:status",
  "cns:config:get",
  "cns:config:update",
  "cns:process",
  "cns:chat",
  "cns:agent-task",
  // CNS Ollama Bridge
  "cns:ollama:status",
  "cns:ollama:health",
  "cns:ollama:models",
  "cns:ollama:inference",
  "cns:ollama:embed",
  "cns:ollama:recommend-model",
  "cns:ollama:performance",
  "cns:ollama:config:update",
  // CNS N8n Bridge
  "cns:n8n:status",
  "cns:n8n:connections",
  "cns:n8n:add-connection",
  "cns:n8n:remove-connection",
  "cns:n8n:test-connection",
  "cns:n8n:workflows",
  "cns:n8n:workflow",
  "cns:n8n:trigger-workflow",
  "cns:n8n:register-webhook",
  "cns:n8n:unregister-webhook",
  "cns:n8n:config:update",
  // Test-only channels
  // These should ALWAYS be guarded with IS_TEST_BUILD in the main process.
  // We can't detect with IS_TEST_BUILD in the preload script because
  // it's a separate process from the main process.
  "supabase:fake-connect-and-set-project",
];

// Add valid receive channels
const validReceiveChannels = [
  "chat:response:chunk",
  "chat:response:end",
  "chat:response:error",
  "app:output",
  "github:flow-update",
  "github:flow-success",
  "github:flow-error",
  "deep-link-received",
  "force-close-detected",
  // Help bot
  "help:chat:response:chunk",
  "help:chat:response:end",
  "help:chat:response:error",
  // MCP consent request from main to renderer
  "mcp:tool-consent-request",
  // Agent tool consent request from main to renderer
  "agent-tool:consent-request",
  // Telemetry events from main to renderer
  "telemetry:event",
  // Voice Assistant events
  "voice:event",
  // Memory System events
  "memory:event",
  // Plugin System events
  "plugin:event",
  // Model Benchmark events
  "benchmark:event",
  // AI Coding Agent events
  "coding-agent:event",
  // Design System Generator events
  "design-system:event",
  // Secrets Vault events
  "secrets-vault:event",
  // Offline Docs Hub events
  "offline-docs:event",
  // Federation inference streaming
  "federation:inference:chunk",
  "federation:inference:done",
  "federation:inference:error",
  // Hybrid Bridge events
  "hybrid-bridge:event",
  // Decentralized Chat events
  "decentralized-chat:event",
  // Compute Network events
  "compute-network:event",
  // WebRTC events
  "webrtc:event",
  // JCN events (publish progress, job completion, etc.)
  "jcn:event",
  // Smart Router events
  "smart-router:event",
  // AI Learning Mode events
  "ai-learning:event",
  // Agent Swarm System events
  "agent-swarm:event",
  // Autonomous Agent System events
  "autonomous-agent:event",
  "autonomous-agent:inference-request",
  // Autonomous Agent Production System events
  "autonomous-prod:event",
  // Model Factory training events
  "model-factory:training-progress",
  "model-factory:training-completed",
  // Agent Factory events
  "agent-factory:event",
  // Hyper Liquid Data Pipeline events
  "hyper-liquid:event",
  "hyper-liquid:progress",
  // OpenClaw Gateway events
  "openclaw:event",
  "openclaw:chat:stream-chunk",
  // OpenClaw Data Pipeline events
  "openclaw:data:event",
  // OpenClaw System Integration events
  "openclaw:system:event",
  // 🦞 OpenClaw Personal AI Assistant events
  "openclaw:event:connected",
  "openclaw:event:disconnected",
  "openclaw:event:error",
  "openclaw:event:gateway-started",
  "openclaw:event:gateway-stopped",
  "openclaw:event:gateway-restarted",
  "openclaw:event:agent-thinking",
  "openclaw:event:agent-tool-call",
  "openclaw:event:agent-response",
  "openclaw:event:agent-completed",
  "openclaw:event:message-received",
  "openclaw:event:message-sent",
  "openclaw:event:channel-connected",
  "openclaw:event:channel-disconnected",
  "openclaw:event:plugin-installed",
  "openclaw:event:plugin-uninstalled",
  "openclaw:event:plugin-enabled",
  "openclaw:event:plugin-disabled",
  "openclaw:event:config-updated",
  "openclaw:event:reconnect-failed",
  "openclaw:event:warning",
  // 🦞 OpenClaw CNS (Central Nervous System) events
  "cns:event:initialized",
  "cns:event:shutdown",
  "cns:event:request:start",
  "cns:event:request:complete",
  "cns:event:request:error",
  "cns:event:message:received",
  "cns:event:agent:completed",
  "cns:event:workflow:triggering",
  "cns:event:workflow:failed",
  "cns:event:ollama:connected",
  "cns:event:ollama:disconnected",
  "cns:event:ollama:inference:start",
  "cns:event:ollama:inference:complete",
  "cns:event:ollama:inference:chunk",
  "cns:event:ollama:inference:error",
  "cns:event:ollama:models:refreshed",
  "cns:event:n8n:connection:added",
  "cns:event:n8n:connection:removed",
  "cns:event:n8n:webhook:registered",
  "cns:event:n8n:webhook:unregistered",
  "cns:event:n8n:event:triggered",
  "cns:event:n8n:event:failed",
  // Studio AI Service events
  "studio-ai:event",
  "studio-ai:chat:stream-chunk",
] as const;

type ValidInvokeChannel = (typeof validInvokeChannels)[number];
type ValidReceiveChannel = (typeof validReceiveChannels)[number];

// Expose protected methods that allow the renderer process to use
// the ipcRenderer without exposing the entire object
contextBridge.exposeInMainWorld("electron", {
  ipcRenderer: {
    invoke: (channel: ValidInvokeChannel, ...args: unknown[]) => {
      if (validInvokeChannels.includes(channel)) {
        return ipcRenderer.invoke(channel, ...args);
      }
      throw new Error(`Invalid channel: ${channel}`);
    },
    on: (
      channel: ValidReceiveChannel,
      listener: (...args: unknown[]) => void,
    ) => {
      if (validReceiveChannels.includes(channel)) {
        const subscription = (
          _event: Electron.IpcRendererEvent,
          ...args: unknown[]
        ) => listener(...args);
        ipcRenderer.on(channel, subscription);
        return () => {
          ipcRenderer.removeListener(channel, subscription);
        };
      }
      throw new Error(`Invalid channel: ${channel}`);
    },
    removeAllListeners: (channel: ValidReceiveChannel) => {
      if (validReceiveChannels.includes(channel)) {
        ipcRenderer.removeAllListeners(channel);
      }
    },
    removeListener: (
      channel: ValidReceiveChannel,
      listener: (...args: unknown[]) => void,
    ) => {
      if (validReceiveChannels.includes(channel)) {
        ipcRenderer.removeListener(channel, listener);
      }
    },
  },
  webFrame: {
    setZoomFactor: (factor: number) => {
      webFrame.setZoomFactor(factor);
    },
    getZoomFactor: () => webFrame.getZoomFactor(),
  },
});
