// See the Electron documentation for details on how to use preload scripts:
// https://www.electronjs.org/docs/latest/tutorial/process-model#preload-scripts

import { contextBridge, ipcRenderer, webFrame } from "electron";

// Whitelist of valid channels
const validInvokeChannels = [
  "analyze-component",
  "apply-visual-editing-changes",
  "get-language-models",
  "get-language-models-by-providers",
  "create-custom-language-model",
  "get-language-model-providers",
  "delete-custom-language-model-provider",
  "create-custom-language-model-provider",
  "edit-custom-language-model-provider",
  "delete-custom-language-model",
  "delete-custom-model",
  "chat:add-dep",
  "chat:message",
  "chat:cancel",
  "chat:stream",
  "chat:count-tokens",
  "create-chat",
  "create-app",
  "copy-app",
  "get-chat",
  "get-chats",
  "search-chats",
  "get-chat-logs",
  "list-apps",
  "get-app",
  "get-app-env-vars",
  "set-app-env-vars",
  "edit-app-file",
  "read-app-file",
  "run-app",
  "stop-app",
  "restart-app",
  "respond-to-app-input",
  "search-app",
  "list-versions",
  "revert-version",
  "checkout-version",
  "get-current-branch",
  "delete-app",
  "rename-app",
  "get-user-settings",
  "set-user-settings",
  "get-env-vars",
  "open-external-url",
  "show-item-in-folder",
  "reset-all",
  "nodejs-status",
  "install-node",
  "select-node-folder",
  "github:start-flow",
  "github:list-repos",
  "github:get-repo-branches",
  "github:is-repo-available",
  "github:create-repo",
  "github:connect-existing-repo",
  "github:push",
  "github:disconnect",
  "neon:create-project",
  "neon:get-project",
  "neon:delete-branch",
  "vercel:save-token",
  "vercel:list-projects",
  "vercel:is-project-available",
  "vercel:create-project",
  "vercel:connect-existing-project",
  "vercel:get-deployments",
  "vercel:disconnect",
  "get-app-version",
  "reload-env-path",
  "get-proposal",
  "approve-proposal",
  "reject-proposal",
  "get-system-debug-info",
  "supabase:list-organizations",
  "supabase:delete-organization",
  "supabase:list-all-projects",
  "supabase:list-branches",
  "supabase:get-edge-logs",
  "supabase:set-app-project",
  "supabase:unset-app-project",
  "local-models:list-ollama",
  "local-models:list-lmstudio",
  "window:minimize",
  "window:maximize",
  "window:close",
  "get-system-platform",
  "upload-to-signed-url",
  "delete-chat",
  "update-chat",
  "delete-messages",
  "start-chat-stream",
  "does-release-note-exist",
  "import-app",
  "check-ai-rules",
  "select-app-folder",
  "check-app-name",
  "rename-branch",
  "clear-session-data",
  "get-user-budget",
  "get-context-paths",
  "set-context-paths",
  "get-app-upgrades",
  "execute-app-upgrade",
  "is-capacitor",
  "sync-capacitor",
  "capacitor:init",
  "open-ios",
  "open-android",
  "check-problems",
  "restart-joy",
  "get-templates",
  "portal:migrate-create",
  // Voice Assistant
  "voice:initialize",
  "voice:shutdown",
  "voice:get-config",
  "voice:update-config",
  "voice:get-state",
  "voice:start-listening",
  "voice:stop-listening",
  "voice:transcribe-file",
  "voice:speak",
  "voice:download-whisper-model",
  "voice:get-installed-models",
  "voice:subscribe",
  "voice:get-capabilities",
  "voice:get-elevenlabs-voices",
  "voice:set-elevenlabs-key",
  // Memory System (Persistent AI Memory)
  "memory:initialize",
  "memory:shutdown",
  "memory:create",
  "memory:get",
  "memory:update",
  "memory:delete",
  "memory:search",
  "memory:fulltext-search",
  "memory:get-context",
  "memory:add-to-context",
  "memory:clear-context",
  "memory:get-profile",
  "memory:update-profile",
  "memory:learn-preference",
  "memory:create-relationship",
  "memory:get-related",
  "memory:consolidate",
  "memory:stats",
  "memory:subscribe",
  // Plugin System (Plugin Marketplace)
  "plugin:initialize",
  "plugin:shutdown",
  "plugin:list",
  "plugin:get",
  "plugin:is-enabled",
  "plugin:install-from-registry",
  "plugin:install-from-url",
  "plugin:install-from-file",
  "plugin:uninstall",
  "plugin:update",
  "plugin:enable",
  "plugin:disable",
  "plugin:get-config",
  "plugin:set-config",
  "plugin:grant-permission",
  "plugin:revoke-permission",
  "plugin:search-registry",
  "plugin:get-registry-plugin",
  "plugin:subscribe",
  // Model Benchmark System
  "benchmark:initialize",
  "benchmark:shutdown",
  "benchmark:run",
  "benchmark:cancel",
  "benchmark:get",
  "benchmark:list",
  "benchmark:delete",
  "benchmark:get-datasets",
  "benchmark:subscribe",
  // AI Coding Agent
  "coding-agent:create-session",
  "coding-agent:end-session",
  "coding-agent:get-session",
  "coding-agent:list-sessions",
  "coding-agent:run-task",
  "coding-agent:approve-action",
  "coding-agent:get-pending-approvals",
  "coding-agent:get-capabilities",
  "coding-agent:subscribe",
  "coding-agent:unsubscribe",
  // Design System Generator
  "design-system:initialize",
  "design-system:create",
  "design-system:generate",
  "design-system:get",
  "design-system:list",
  "design-system:delete",
  "design-system:update-tokens",
  "design-system:generate-component",
  "design-system:update-component",
  "design-system:delete-component",
  "design-system:export",
  "design-system:subscribe",
  "design-system:unsubscribe",
  // Secrets Vault
  "secrets-vault:initialize",
  "secrets-vault:check-exists",
  "secrets-vault:create",
  "secrets-vault:unlock",
  "secrets-vault:lock",
  "secrets-vault:delete",
  "secrets-vault:change-password",
  "secrets-vault:get-status",
  "secrets-vault:set-auto-lock",
  "secrets-vault:create-secret",
  "secrets-vault:get-secret",
  "secrets-vault:update-secret",
  "secrets-vault:delete-secret",
  "secrets-vault:list-secrets",
  "secrets-vault:get-stats",
  "secrets-vault:create-backup",
  "secrets-vault:restore-backup",
  "secrets-vault:list-backups",
  "secrets-vault:delete-backup",
  "secrets-vault:forget-password",
  "secrets-vault:link-wallet",
  "secrets-vault:unlink-wallet",
  "secrets-vault:get-owner-wallet",
  "secrets-vault:subscribe",
  "secrets-vault:unsubscribe",
  // Vault AI/runtime integration
  "secrets-vault:get-context",
  "secrets-vault:get-by-name",
  "secrets-vault:resolve-env-vars",
  "secrets-vault:sync-from-settings",
  // Offline Docs Hub
  "offline-docs:initialize",
  "offline-docs:shutdown",
  "offline-docs:get-bundled",
  "offline-docs:create-collection",
  "offline-docs:get-collection",
  "offline-docs:list-collections",
  "offline-docs:update-collection",
  "offline-docs:delete-collection",
  "offline-docs:get-document",
  "offline-docs:list-documents",
  "offline-docs:delete-document",
  "offline-docs:search",
  "offline-docs:import-folder",
  "offline-docs:import-url",
  "offline-docs:get-import-progress",
  "offline-docs:get-stats",
  "offline-docs:subscribe",
  "offline-docs:unsubscribe",
  // MCP
  "mcp:list-servers",
  "mcp:create-server",
  "mcp:update-server",
  "mcp:delete-server",
  "mcp:list-tools",
  "mcp:get-tool-consents",
  "mcp:set-tool-consent",
  // MCP consent response from renderer to main
  "mcp:tool-consent-response",
  // Agent Tools (Local Agent v2)
  "agent-tool:get-tools",
  "agent-tool:set-consent",
  "agent-tool:consent-response",
  // Agent Builder - System Prompt AI Generation
  "agent-builder:generate-system-prompt",
  "agent-builder:update-system-prompt-with-ai",
  "agent-builder:analyze-system-prompt",
  // Help
  "take-screenshot",
  // Help bot
  "help:chat:start",
  "help:chat:cancel",
  // Joy Assistant
  "joy-assistant:chat",
  "joy-assistant:cancel",
  "joy-assistant:suggestions",
  "joy-assistant:history",
  "joy-assistant:clear",
  "joy-assistant:set-mode",
  "joy-assistant:execute-action",
  // Prompts
  "prompts:list",
  "prompts:create",
  "prompts:update",
  "prompts:delete",
  // Library
  "library:upload-dialog",
  "library:import-buffer",
  "library:list",
  "library:get",
  "library:get-content",
  "library:update",
  "library:delete",
  "library:store-to-ipfs",
  "library:pin-to-remote",
  "library:store-to-arweave",
  "library:store-to-filecoin",
  // adding app to favorite
  "add-to-favorite",
  "github:clone-repo-from-url",
  "get-latest-security-review",
  // Agent Memory (Long-Term + Short-Term)
  "agent-memory:config:get",
  "agent-memory:config:upsert",
  "agent-memory:ltm:create",
  "agent-memory:ltm:get",
  "agent-memory:ltm:list",
  "agent-memory:ltm:update",
  "agent-memory:ltm:delete",
  "agent-memory:ltm:search",
  "agent-memory:stm:set",
  "agent-memory:stm:list",
  "agent-memory:stm:delete",
  "agent-memory:stm:clear",
  // Agent Builder
  "agent:create",
  "agent:get",
  "agent:list",
  "agent:update",
  "agent:delete",
  "agent:duplicate",
  "agent:tool:create",
  "agent:tool:list",
  "agent:tool:update",
  "agent:tool:delete",
  "agent:workflow:create",
  "agent:workflow:list",
  "agent:workflow:update",
  "agent:workflow:delete",
  "agent:deploy",
  "agent:deployment:list",
  "agent:deployment:stop",
  "agent:test:create",
  "agent:test:list",
  "agent:kb:create",
  "agent:kb:list",
  "agent:ui:create",
  "agent:ui:list",
  "agent:export:json",
  "agent:export:standalone",
  "agent:export:docker",
  "agent:export:web-chat",
  "agent:export:embed-snippet",
  // Agent Sharing
  "agent:share:create",
  "agent:share:get",
  "agent:share:update",
  "agent:share:delete",
  "agent:share:generate-codes",
  "agent:share:save-app-as-template",
  // Agent Creation Pipeline (NLP → Agent)
  "agent:intent:quick-detect",
  "agent:intent:detect",
  "agent:blueprint:generate",
  "agent:pipeline:detect-and-generate",
  // Agent Markdown Template (.agent.md)
  "agent:template:parse",
  "agent:template:export",
  // Agent UI Builder
  "agent:ui:templates",
  "agent:ui:themes",
  "agent:ui:recommend-config",
  "agent:ui:generate",
  "agent:ui:export",
  "agent:ui:preview-template",
  "agent:ui:create-config",
  // Agent Triggers & Stack Builder
  "agent:trigger:create",
  "agent:trigger:list",
  "agent:trigger:update",
  "agent:trigger:delete",
  "agent:trigger:activate",
  "agent:trigger:pause",
  "agent:tool-catalog:list",
  "agent:tool-catalog:by-category",
  "agent:tool-catalog:search",
  "agent:tool-catalog:add",
  "agent:stack:build",
  "agent:stack:get",
  "agent:stack:sync-n8n",
  // Agent Workspace — Per-agent task management, knowledge sources, execution engine
  "agent:workspace:task:create",
  "agent:workspace:task:list",
  "agent:workspace:task:get",
  "agent:workspace:task:update",
  "agent:workspace:task:delete",
  "agent:workspace:task:execute",
  "agent:workspace:task:executions",
  "agent:workspace:knowledge:add",
  "agent:workspace:knowledge:list",
  "agent:workspace:knowledge:get",
  "agent:workspace:knowledge:update",
  "agent:workspace:knowledge:delete",
  "agent:workspace:knowledge:sync",
  "agent:workspace:knowledge:query",
  "agent:workspace:get",
  // Agent Orchestrator — Autonomous Meta-Agent System
  "orchestrator:initialize",
  "orchestrator:shutdown",
  "orchestrator:status",
  "orchestrator:submit-task",
  "orchestrator:get",
  "orchestrator:list",
  "orchestrator:cancel",
  "orchestrator:pause",
  "orchestrator:resume",
  "orchestrator:dashboard",
  "orchestrator:meta-agent",
  "orchestrator:templates",
  "orchestrator:config:execution:get",
  "orchestrator:config:execution:update",
  "orchestrator:config:communication:get",
  "orchestrator:config:communication:update",
  "orchestrator:config:longterm:get",
  "orchestrator:config:longterm:update",
  "orchestrator:subscribe",
  // External Services Management
  "services:list",
  "services:status:all",
  "services:status",
  "services:start",
  "services:stop",
  "services:restart",
  "services:start:all",
  "services:stop:all",
  // Tailscale VPN
  "tailscale:status",
  "tailscale:config:get",
  "tailscale:config:save",
  "tailscale:service-urls",
  // Celestia Blob DA Layer
  "celestia:blob:submit",
  "celestia:blob:submit-json",
  "celestia:blob:submit-file",
  "celestia:blob:get",
  "celestia:blob:get-at-height",
  "celestia:blob:list",
  "celestia:blob:stats",
  "celestia:blob:hash",
  "celestia:blob:verify",
  "celestia:status",
  "celestia:config:get",
  "celestia:config:update",
  "celestia:config:reset",
  "celestia:namespace:generate",
  "celestia:wallet:validate",
  // Creator Lifecycle Engine
  "lifecycle:create",
  "lifecycle:verify",
  "lifecycle:use",
  "lifecycle:receipt",
  "lifecycle:reward:issue",
  "lifecycle:reward:summary",
  "lifecycle:reputation:get",
  "lifecycle:reputation:recompute",
  "lifecycle:feedback:create",
  "lifecycle:feedback:list",
  "lifecycle:feedback:resolve",
  "lifecycle:feedback:auto",
  "lifecycle:asset:summary",
  "lifecycle:stats",
  "lifecycle:streak:update",
  // n8n Integration
  "n8n:start",
  "n8n:stop",
  "n8n:status",
  "n8n:set-api-key",
  "n8n:refresh-auth",
  "n8n:db:configure",
  "n8n:db:get-config",
  "n8n:workflow:create",
  "n8n:workflow:update",
  "n8n:workflow:get",
  "n8n:workflow:list",
  "n8n:workflow:delete",
  "n8n:workflow:activate",
  "n8n:workflow:deactivate",
  "n8n:workflow:execute",
  "n8n:workflow:generate",
  "n8n:meta-builder:create",
  "n8n:setup-ollama",
  "n8n:agent:send-message",
  "n8n:agent:get-messages",
  "n8n:agent:create-collaboration",
  "n8n:agent:get-collaboration",
  "n8n:agent:list-collaborations",
  "n8n:agent:create-collab-workflow",
  // Trustless Local Inference
  "trustless:initialize",
  "trustless:shutdown",
  "trustless:check-providers",
  "trustless:list-models",
  "trustless:get-model-info",
  "trustless:run-inference",
  "trustless:start-stream",
  "trustless:verify-record",
  "trustless:get-record",
  "trustless:list-records",
  "trustless:export-proof",
  "trustless:import-proof",
  "trustless:pin-record",
  "trustless:unpin-record",
  "trustless:create-batch-proof",
  "trustless:verify-batch-proof",
  "trustless:helia-status",
  "trustless:get-stats",
  // Trustless Conversations
  "trustless:create-conversation",
  "trustless:get-conversation",
  "trustless:list-conversations",
  "trustless:delete-conversation",
  "trustless:update-conversation",
  "trustless:send-message",
  // IPLD Receipts
  "receipt:create",
  "receipt:list",
  "receipt:get",
  "receipt:verify",
  // Export Service
  "export:to-spreadsheet",
  "export:to-document",
  "export:capabilities",
  // LibreOffice Integration
  "libreoffice:status",
  "libreoffice:refresh-status",
  "libreoffice:create",
  "libreoffice:list",
  "libreoffice:get",
  "libreoffice:delete",
  "libreoffice:update-metadata",
  "libreoffice:export",
  "libreoffice:open",
  "libreoffice:download",
  "libreoffice:show-in-folder",
  "libreoffice:get-directory",
  "libreoffice:ensure-ready",
  "libreoffice:shutdown",
  "libreoffice:stream-generate",
  "libreoffice:read-content",
  "libreoffice:update-content",
  "libreoffice:ai-assist",
  // Marketplace Integration
  "marketplace:status",
  "marketplace:connect",
  "marketplace:disconnect",
  "marketplace:get-profile",
  "marketplace:list-assets",
  "marketplace:get-asset",
  "marketplace:publish",
  "marketplace:publish-model",
  "marketplace:update-asset",
  "marketplace:unpublish",
  "marketplace:earnings",
  "marketplace:export-zip",
  "marketplace:deployment-status",
  "marketplace:open",
  "marketplace:get-url",
  // JoyMarketplace.io Sync (Local → Online)
  "marketplace-sync:get-config",
  "marketplace-sync:connect",
  "marketplace-sync:disconnect",
  "marketplace-sync:get-store-from-domain",
  "marketplace-sync:verify-domain",
  "marketplace-sync:set-default-store",
  "marketplace-sync:get-default-store",
  "marketplace-sync:sync-listing",
  "marketplace-sync:batch-sync",
  "marketplace-sync:ingest-receipt",
  "marketplace-sync:verify-receipt",
  "marketplace-sync:configure-pinning",
  "marketplace-sync:pin-receipt",
  "marketplace-sync:pin-receipts-batch",
  "marketplace-sync:get-pin-status",
  "marketplace-sync:unpin-receipt",
  "marketplace-sync:get-gateway-url",
  "marketplace-sync:verify-payout",
  "marketplace-sync:get-usdc-balance",
  "marketplace-sync:get-nft-metadata",
  "marketplace-sync:get-owned-nfts",
  // Marketplace Browse (public discovery)
  "marketplace:browse",
  "marketplace:asset-detail",
  "marketplace:install-asset",
  "marketplace:featured",
  "marketplace:categories",
  // Subgraph — On-chain marketplace data (Goldsky)
  "subgraph:my-assets",
  "subgraph:tokens",
  "subgraph:user-balances",
  "subgraph:purchases",
  "subgraph:drop-stats",
  "subgraph:user-stores",
  "subgraph:all-stores",
  "subgraph:user-domains",
  "subgraph:all-domains",
  "subgraph:store-stats",
  // Subgraph — Marketplace subgraph (assets, listings, licenses)
  "subgraph:marketplace-assets",
  "subgraph:marketplace-listings",
  "subgraph:ai-models",
  "subgraph:user-licenses",
  "subgraph:user-receipts",
  "subgraph:marketplace-stats",
  // Creator Dashboard
  "creator:get-overview",
  "creator:get-all-assets",
  "creator:get-earnings-breakdown",
  "creator:get-analytics",
  // Agent Marketplace Publishing
  "agent:publish-to-marketplace",
  "agent:unpublish",
  "agent:update-listing",
  // Workflow Marketplace Publishing
  "workflow:publish-to-marketplace",
  "workflow:install-from-marketplace",
  "workflow:unpublish",
  "workflow:list-published",
  // Web Scraper & Dataset Management
  "scraper:status",
  "scraper:config:list",
  "scraper:config:save",
  "scraper:config:delete",
  "scraper:templates",
  "scraper:job:start",
  "scraper:job:status",
  "scraper:job:list",
  "scraper:job:cancel",
  "scraper:dataset:list",
  "scraper:dataset:get",
  "scraper:dataset:preview",
  "scraper:dataset:export",
  "scraper:dataset:delete",
  "scraper:dataset:create",
  "scraper:dataset:import",
  "scraper:quick-scrape",
  // Scraping Engine v2 — Best-in-class web scraping
  "scraping:init",
  "scraping:scrape-url",
  "scraping:preview",
  "scraping:create-job",
  "scraping:start-job",
  "scraping:pause-job",
  "scraping:cancel-job",
  "scraping:delete-job",
  "scraping:get-job",
  "scraping:list-jobs",
  "scraping:templates",
  "scraping:detect-schema",
  "scraping:auto-tag",
  "scraping:check-robots",
  "scraping:parse-sitemap",
  "scraping:parse-feed",
  "scraping:nlp-configure",
  // Scraping Engine v3 — Orchestrator-backed multi-engine scraping
  "scraping:v3:quick-scrape",
  "scraping:v3:probe-url",
  "scraping:v3:create-job",
  "scraping:v3:run-job",
  "scraping:v3:pause-job",
  "scraping:v3:cancel-job",
  "scraping:v3:resume-job",
  "scraping:v3:delete-job",
  "scraping:v3:get-job",
  "scraping:v3:list-jobs",
  "scraping:v3:get-results",
  "scraping:v3:export",
  "scraping:v3:detect-pii",
  "scraping:v3:create-schedule",
  "scraping:v3:list-schedules",
  "scraping:v3:toggle-schedule",
  "scraping:v3:delete-schedule",
  "scraping:v3:create-template",
  "scraping:v3:list-templates",
  "scraping:v3:get-template",
  "scraping:v3:delete-template",
  "scraping:v3:list-sessions",
  "scraping:v3:delete-session",
  "scraping:v3:import-cookies",
  // Vector Store — sqlite-vec local vector search & RAG
  "vector:init",
  "vector:create-collection",
  "vector:list-collections",
  "vector:get-collection",
  "vector:delete-collection",
  "vector:add-documents",
  "vector:delete-document",
  "vector:list-documents",
  "vector:search",
  "vector:rag",
  "vector:get-stats",
  "vector:set-embedding-model",
  // Embedding Pipeline
  "embedding:init",
  "embedding:detect-models",
  "embedding:set-model",
  "embedding:get-status",
  "embedding:ingest-document",
  "embedding:ingest-file",
  "embedding:ingest-url",
  "embedding:ingest-batch",
  "embedding:retrieve",
  "embedding:retrieve-for-chat",
  "embedding:embed-query",
  "embedding:cancel-all",
  // Model Download Manager
  "model-manager:detect-hardware",
  "model-manager:get-catalog",
  "model-manager:get-filtered-catalog",
  "model-manager:pull-model",
  "model-manager:delete-model",
  "model-manager:list-installed",
  "model-manager:get-pull-status",
  // Asset Studio
  "assets:stats",
  "assets:list",
  "assets:list-all",
  "assets:get",
  "assets:delete",
  "assets:update",
  "assets:export",
  "assets:import",
  "assets:open-folder",
  "assets:read-file",
  "assets:create:algorithm",
  "assets:create:schema",
  "assets:create:prompt",
  "assets:create:ui-component",
  "assets:create:api",
  "assets:create:training-data",
  "assets:get-directory",
  // Image Studio
  "image-studio:generate",
  "image-studio:edit",
  "image-studio:list",
  "image-studio:get",
  "image-studio:delete",
  "image-studio:save-to-disk",
  "image-studio:open-in-folder",
  "image-studio:available-providers",
  "image-studio:read-image",
  "image-studio:enhance-prompt",
  "image-studio:upscale",
  "image-studio:variations",
  // Video Studio
  "video-studio:generate",
  "video-studio:list",
  "video-studio:get",
  "video-studio:delete",
  "video-studio:save-to-disk",
  "video-studio:open-in-folder",
  "video-studio:available-providers",
  "video-studio:read-video",
  "video-studio:read-thumbnail",
  "video-studio:enhance-prompt",
  "video-studio:extract-frames",
  // Dataset Studio (Multimodal Dataset Creation with Provenance)
  "dataset-studio:create-dataset",
  "dataset-studio:list-datasets",
  "dataset-studio:get-dataset",
  "dataset-studio:update-dataset",
  "dataset-studio:delete-dataset",
  "dataset-studio:refresh-stats",
  "dataset-studio:add-item-from-file",
  "dataset-studio:add-generated-item",
  "dataset-studio:update-item-labels",
  "dataset-studio:update-quality-signals",
  "dataset-studio:list-items",
  "dataset-studio:get-item",
  "dataset-studio:delete-item",
  "dataset-studio:build-manifest",
  "dataset-studio:create-splits",
  "dataset-studio:sign-manifest",
  "dataset-studio:get-manifest",
  "dataset-studio:create-generation-job",
  "dataset-studio:get-job-status",
  "dataset-studio:list-jobs",
  "dataset-studio:init-p2p-sync",
  "dataset-studio:get-p2p-sync-status",
  "dataset-studio:get-content",
  "dataset-studio:export-dataset",
  // NFT Marketplace
  "nft:chunk-asset",
  "nft:get-chunks",
  "nft:create-listing",
  "nft:bulk-create-listings",
  "nft:list-all",
  "nft:list-by-asset",
  "nft:get-listing",
  "nft:update-pricing",
  "nft:update-status",
  "nft:publish",
  "nft:bulk-publish",
  "nft:delete-listing",
  "nft:portfolio",
  "nft:stats",
  // Federation & P2P Marketplace
  "federation:create-identity",
  "federation:get-identity",
  "federation:get-peers",
  "federation:get-connected-peers",
  "federation:connect-peer",
  "federation:disconnect-peer",
  "federation:add-peer",
  "federation:bootstrap:list",
  "federation:bootstrap:add",
  "federation:bootstrap:remove",
  "federation:bootstrap:import",
  "federation:dht-put",
  "federation:dht-get",
  "federation:model-chunk-serve",
  "federation:model-chunk-request",
  "federation:model-chunk-announce",
  "federation:model-chunk-find",
  "federation:route-inference",
  "federation:execute-inference",
  "federation:execute-inference-stream",
  "federation:model-chunk-listing:create",
  "federation:model-chunk-listing:list",
  "federation:model-chunk-purchase:create",
  "federation:model-chunk-purchase:list",
  "federation:model-chunk-escrow:create",
  "federation:create-listing",
  "federation:get-listings",
  "federation:search-listings",
  "federation:initiate-transaction",
  "federation:update-transaction",
  "federation:get-transactions",
  "federation:create-escrow",
  "federation:send-message",
  "federation:get-conversations",
  "federation:get-stats",
  // Sovereign Data (Local-First Encrypted Storage)
  "sovereign:get-vault",
  "sovereign:update-vault-config",
  "sovereign:enable-network",
  "sovereign:store-data",
  "sovereign:retrieve-data",
  "sovereign:list-data",
  "sovereign:delete-data",
  "sovereign:sync-to-network",
  "sovereign:pin-to-ipfs",
  "sovereign:store-on-arweave",
  "sovereign:run-local-inference",
  "sovereign:share-data",
  "sovereign:revoke-access",
  "sovereign:update-consent",
  "sovereign:queue-sync",
  "sovereign:queue-share",
  "sovereign:list-outbox",
  "sovereign:process-outbox",
  "sovereign:policy-audit",
  "sovereign:create-listing",
  "sovereign:get-listings",
  "sovereign:get-purchases",
  "sovereign:record-purchase",
  "sovereign:export-data",
  "sovereign:import-data",
  // Decentralized Deployment (4everland, Fleek, IPFS, Arweave, etc.)
  "decentralized:save-credentials",
  "decentralized:get-credentials",
  "decentralized:remove-credentials",
  "decentralized:deploy",
  "decentralized:get-deployments",
  "decentralized:get-deployment",
  "decentralized:check-pin-status",
  "decentralized:get-platforms",
  // Auto-Deploy (one-click build + push + deploy)
  "deploy:auto-deploy",
  "deploy:check-completeness",
  // Project Management
  "project:create",
  "project:list",
  "project:get",
  "project:update",
  "project:delete",
  // Hybrid Bridge (Local/Cloud Integration)
  "hybrid-bridge:start",
  "hybrid-bridge:stop",
  "hybrid-bridge:status",
  "hybrid-bridge:config:update",
  "hybrid-bridge:config:get",
  "hybrid-bridge:service:add",
  "hybrid-bridge:service:remove",
  "hybrid-bridge:service:reconnect",
  "hybrid-bridge:service:list",
  "hybrid-bridge:sync:run",
  "hybrid-bridge:sync:state",
  "hybrid-bridge:sync:clear-errors",
  "hybrid-bridge:request",
  "hybrid-bridge:n8n:restart",
  "hybrid-bridge:n8n:health",
  // Decentralized Chat (Wallet-to-Wallet)
  "dchat:identity:create",
  "dchat:identity:get",
  "dchat:identity:update",
  "dchat:conversation:create",
  "dchat:conversation:get",
  "dchat:conversation:list",
  "dchat:conversation:get-direct",
  "dchat:message:send",
  "dchat:message:get",
  "dchat:message:decrypt",
  "dchat:pin:pull",
  "dchat:sync:online",
  "dchat:offline:check",
  "dchat:presence:broadcast",
  "dchat:typing:send",
  "dchat:status",
  "dchat:test:encryption",
  "dchat:test:pin",
  "dchat:test:connectivity",
  // Decentralized Chat — Privacy Layer (Onion Routing, Double Ratchet, Cover Traffic)
  "dchat:privacy:init",
  "dchat:privacy:status",
  "dchat:privacy:shutdown",
  "dchat:ice:discover",
  "dchat:ice:register-relay",
  "dchat:ice:health-check",
  "dchat:ice:status",
  "dchat:circuit:build",
  "dchat:relay:status",
  "dchat:private:send",
  "dchat:ratchet:init",
  "dchat:signal:send",
  "dchat:cover-traffic:start",
  "dchat:cover-traffic:stop",
  "dchat:nat:detect",
  // Compute Network (Decentralized AI Inference)
  "compute-network:initialize",
  "compute-network:shutdown",
  "compute-network:get-status",
  "compute-network:get-config",
  "compute-network:update-config",
  "compute-network:get-peers",
  "compute-network:get-peer",
  "compute-network:get-connections",
  "compute-network:connect-peer",
  "compute-network:disconnect-peer",
  "compute-network:fetch-content",
  "compute-network:pin-content",
  "compute-network:unpin-content",
  "compute-network:store-content",
  "compute-network:get-fetch-progress",
  "compute-network:create-job",
  "compute-network:accept-job",
  "compute-network:cancel-job",
  "compute-network:get-jobs",
  "compute-network:get-job",
  "compute-network:get-active-jobs",
  "compute-network:get-pending-jobs",
  "compute-network:request-validation",
  "compute-network:get-validation-requests",
  "compute-network:get-job-stats",
  "compute-network:get-system-metrics",
  "compute-network:get-network-metrics",
  "compute-network:subscribe",
  // WebRTC (Decentralized P2P Communication)
  "webrtc:init",
  "webrtc:status",
  "webrtc:ice:list",
  "webrtc:ice:register",
  "webrtc:peer:connect",
  "webrtc:peer:disconnect",
  "webrtc:peer:list",
  "webrtc:data:send",
  "webrtc:signaling:receive",
  "webrtc:call:start",
  "webrtc:call:answer",
  "webrtc:call:end",
  "webrtc:call:mute",
  "webrtc:call:video",
  // JoyCreate Node (JCN) - Local Asset Publishing & Inference
  "jcn:auth:createToken",
  "jcn:auth:verifyToken",
  "jcn:auth:signMessage",
  "jcn:publish:asset",
  "jcn:publish:getStatus",
  "jcn:publish:list",
  "jcn:publish:retry",
  "jcn:job:submit",
  "jcn:job:getStatus",
  "jcn:job:list",
  "jcn:job:cancel",
  "jcn:bundle:build",
  "jcn:bundle:verify",
  "jcn:bundle:get",
  "jcn:bundle:list",
  "jcn:storage:pin",
  "jcn:storage:fetch",
  "jcn:storage:verify",
  "jcn:license:register",
  "jcn:license:verify",
  "jcn:license:list",
  "jcn:license:revoke",
  "jcn:key:generate",
  "jcn:key:import",
  "jcn:key:list",
  "jcn:key:delete",
  "jcn:key:sign",
  "jcn:key:verify",
  "jcn:key:rotate",
  "jcn:admin:auditLog",
  // Self-Sovereign Identity (SSI)
  "ssi:identity:create",
  "ssi:identity:get",
  "ssi:identity:list",
  "ssi:identity:update",
  "ssi:identity:deactivate",
  "ssi:identity:resolve",
  "ssi:identity:link",
  "ssi:credential:issue",
  "ssi:credential:verify",
  "ssi:credential:list",
  "ssi:credential:get",
  "ssi:credential:revoke",
  "ssi:credential:import",
  "ssi:credential:export",
  "ssi:presentation:create",
  "ssi:presentation:verify",
  "ssi:presentation:list",
  "ssi:anchor:submit",
  "ssi:anchor:verify",
  "ssi:anchor:history",
  // Email Agent System
  "email:account:add",
  "email:account:list",
  "email:account:get",
  "email:account:update",
  "email:account:remove",
  "email:folders:list",
  "email:messages:list",
  "email:messages:list-unified",
  "email:messages:get",
  "email:messages:thread",
  "email:messages:search",
  "email:messages:mark-read",
  "email:messages:mark-starred",
  "email:messages:move",
  "email:messages:delete",
  "email:send",
  "email:drafts:save",
  "email:drafts:list",
  "email:drafts:delete",
  "email:ai:triage",
  "email:ai:triage-batch",
  "email:ai:summarize",
  "email:ai:compose",
  "email:ai:adjust-tone",
  "email:ai:smart-replies",
  "email:ai:follow-ups",
  "email:ai:daily-digest",
  "email:agent:submit",
  "email:agent:approve",
  "email:agent:reject",
  "email:agent:pending",
  "email:sync:now",
  "email:sync:start-all",
  "email:sync:stop-all",
  "email:stats",
  "email:orchestrator:start",
  "email:orchestrator:stop",
  "email:orchestrator:status",
  "email:orchestrator:set-auto-triage",
  "email:orchestrator:set-auto-actions",
  "email:orchestrator:update-config",
  "email:orchestrator:rules:list",
  "email:orchestrator:rules:add",
  "email:orchestrator:rules:update",
  "email:orchestrator:rules:remove",
  "jcn:admin:replay",
  "jcn:admin:recover",
  "jcn:admin:stats",
  "jcn:chain:pollPending",
  "jcn:chain:checkReorgs",
  // Smart Router (Intelligent Local/Cloud Routing)
  "smart-router:route",
  "smart-router:record-result",
  "smart-router:list-providers",
  "smart-router:get-provider",
  "smart-router:register-provider",
  "smart-router:update-provider-status",
  "smart-router:get-config",
  "smart-router:update-config",
  "smart-router:get-stats",
  // AI Learning Mode
  "ai-learning:initialize",
  "ai-learning:shutdown",
  "ai-learning:create-profile",
  "ai-learning:get-profile",
  "ai-learning:list-profiles",
  "ai-learning:update-profile",
  "ai-learning:delete-profile",
  "ai-learning:activate-profile",
  "ai-learning:get-active-profile",
  "ai-learning:learn-pattern",
  "ai-learning:get-pattern",
  "ai-learning:list-patterns",
  "ai-learning:update-pattern",
  "ai-learning:add-pattern-example",
  "ai-learning:delete-pattern",
  "ai-learning:search-patterns",
  "ai-learning:record-feedback",
  "ai-learning:list-feedback",
  "ai-learning:get-style-guide",
  "ai-learning:update-style-guide",
  "ai-learning:get-communication-prefs",
  "ai-learning:update-communication-prefs",
  "ai-learning:generate-context",
  "ai-learning:get-stats",
  "ai-learning:subscribe",
  "ai-learning:unsubscribe",
  // Agent Swarm System
  "agent-swarm:initialize",
  "agent-swarm:shutdown",
  "agent-swarm:create-swarm",
  "agent-swarm:get-swarm",
  "agent-swarm:list-swarms",
  "agent-swarm:update-swarm",
  "agent-swarm:start-swarm",
  "agent-swarm:pause-swarm",
  "agent-swarm:terminate-swarm",
  "agent-swarm:delete-swarm",
  "agent-swarm:spawn-agent",
  "agent-swarm:get-agent",
  "agent-swarm:list-agents",
  "agent-swarm:get-agent-children",
  "agent-swarm:get-agent-lineage",
  "agent-swarm:update-agent",
  "agent-swarm:start-agent",
  "agent-swarm:stop-agent",
  "agent-swarm:terminate-agent",
  "agent-swarm:replicate-agent",
  "agent-swarm:list-replications",
  "agent-swarm:start-witness",
  "agent-swarm:record-observation",
  "agent-swarm:add-witness-insight",
  "agent-swarm:end-witness",
  "agent-swarm:get-witness",
  "agent-swarm:list-witnesses",
  "agent-swarm:assign-task",
  "agent-swarm:delegate-task",
  "agent-swarm:complete-task",
  "agent-swarm:fail-task",
  "agent-swarm:send-message",
  "agent-swarm:acknowledge-message",
  "agent-swarm:list-messages",
  "agent-swarm:share-knowledge",
  "agent-swarm:apply-knowledge",
  "agent-swarm:rate-knowledge",
  "agent-swarm:search-knowledge",
  "agent-swarm:get-knowledge",
  "agent-swarm:list-knowledge",
  "agent-swarm:get-swarm-stats",
  "agent-swarm:get-agent-stats",
  "agent-swarm:get-recent-events",
  "agent-swarm:subscribe",
  "agent-swarm:unsubscribe",
  "agent-swarm:execute-task",
  "agent-swarm:get-task-output",
  "agent-swarm:agent-chat",
  "agent-swarm:get-chat-history",
  // Autonomous Agent System - Fully autonomous perpetually growing AI
  "autonomous-agent:initialize",
  "autonomous-agent:shutdown",
  "autonomous-agent:create-agent",
  "autonomous-agent:get-agent",
  "autonomous-agent:list-agents",
  "autonomous-agent:activate-agent",
  "autonomous-agent:terminate-agent",
  "autonomous-agent:replicate-agent",
  "autonomous-agent:get-agent-stats",
  "autonomous-agent:create-mission",
  "autonomous-agent:get-mission",
  "autonomous-agent:list-missions",
  "autonomous-agent:get-artifact",
  "autonomous-agent:list-artifacts",
  "autonomous-agent:transcribe-audio",
  "autonomous-agent:synthesize-speech",
  "autonomous-agent:get-events",
  "autonomous-agent:subscribe",
  "autonomous-agent:unsubscribe",
  "autonomous-agent:inference-response",
  // Background Mission Management
  "mission:start",
  "mission:get",
  "mission:list",
  "mission:pause",
  "mission:resume",
  "mission:cancel",
  "mission:delete",
  "mission:update",
  // Autonomous Agent Production - Resource monitoring, security, scheduling, approvals, etc.
  "autonomous-prod:initialize",
  "autonomous-prod:shutdown",
  "autonomous-prod:get-resources",
  "autonomous-prod:get-throttle-state",
  "autonomous-prod:check-permission",
  "autonomous-prod:get-audit-log",
  "autonomous-prod:create-schedule",
  "autonomous-prod:get-schedules",
  "autonomous-prod:request-approval",
  "autonomous-prod:respond-approval",
  "autonomous-prod:get-pending-approvals",
  "autonomous-prod:get-templates",
  "autonomous-prod:get-template",
  "autonomous-prod:create-notification",
  "autonomous-prod:get-notifications",
  "autonomous-prod:mark-notification-read",
  "autonomous-prod:get-system-health",
  "autonomous-prod:check-quota",
  "autonomous-prod:record-quota-usage",
  "autonomous-prod:add-knowledge-node",
  "autonomous-prod:add-knowledge-edge",
  "autonomous-prod:query-knowledge",
  "autonomous-prod:record-event",
  "autonomous-prod:get-metrics",
  "autonomous-prod:create-backup",
  "autonomous-prod:list-backups",
  "autonomous-prod:subscribe",
  "autonomous-prod:unsubscribe",
  // Model Factory - LoRA/QLoRA training for low GPU systems
  "model-factory:get-system-info",
  "model-factory:create-job",
  "model-factory:start-training",
  // Dataset Training Center — Train on Dataset Studio datasets
  "training:train-on-dataset",
  "training:get-status",
  "training:list-jobs",
  "training:cancel",
  "training:list-trained-models",
  "training:list-base-models",
  "training:get-system-info",
  "model-factory:cancel-training",
  "model-factory:get-job",
  "model-factory:list-jobs",
  "model-factory:export-model",
  "model-factory:import-adapter",
  "model-factory:list-adapters",
  "model-factory:delete-adapter",
  // HuggingFace Hub - Model/dataset search, download, push
  "hf:search-models",
  "hf:search-datasets",
  "hf:model-info",
  "hf:download-model",
  "hf:download-dataset",
  "hf:push-adapter",
  "hf:auth-status",
  // Agent Factory - Custom AI agent creation and training
  "agent-factory:create",
  "agent-factory:get",
  "agent-factory:list",
  "agent-factory:update",
  "agent-factory:delete",
  "agent-factory:duplicate",
  "agent-factory:start-training",
  "agent-factory:training-status",
  "agent-factory:cancel-training",
  "agent-factory:add-skill",
  "agent-factory:remove-skill",
  "agent-factory:list-skills",
  "agent-factory:add-tool",
  "agent-factory:remove-tool",
  "agent-factory:list-tools",
  "agent-factory:test",
  "agent-factory:set-adapter",
  "agent-factory:list-templates",
  "agent-factory:create-from-template",
  "agent-factory:export",
  "agent-factory:import",
  // Privacy-Preserving Inference Bridge - Local-first AI
  "privacy-inference:initialize",
  "privacy-inference:get-state",
  "privacy-inference:update-config",
  "privacy-inference:get-config",
  "privacy-inference:infer",
  "privacy-inference:local-complete",
  "privacy-inference:agent-task",
  "privacy-inference:get-stats",
  "privacy-inference:reset-stats",
  "privacy-inference:register-adapter",
  "privacy-inference:register-agent",
  "privacy-inference:add-trusted-peer",
  "privacy-inference:remove-trusted-peer",
  "privacy-inference:get-privacy-profiles",
  "privacy-inference:get-routing-profiles",
  // Deployed Contracts & NFT-Gated Inference Access
  "contracts:configure",
  "contracts:fetch-deployed",
  "contracts:fetch-inference-nfts",
  "contracts:get-owned-nfts",
  "contracts:get-for-asset",
  "contracts:verify-access",
  "contracts:request-decryption-key",
  "contracts:deploy",
  "contracts:mint-access-nft",
  "contracts:record-usage",
  "contracts:get-audit-logs",
  // Data Sovereignty & Monetization
  "sovereignty:get-vault",
  "sovereignty:update-vault",
  "sovereignty:protect",
  "sovereignty:batch-protect",
  "sovereignty:get-asset",
  "sovereignty:list-assets",
  "sovereignty:delete-asset",
  "sovereignty:verify-access",
  "sovereignty:revoke-access",
  "sovereignty:grant-access",
  "sovereignty:update-monetization",
  "sovereignty:enable-monetization",
  "sovereignty:report-harvester",
  "sovereignty:get-blocklist",
  "sovereignty:update-anti-harvesting",
  "sovereignty:get-analytics",
  "sovereignty:get-access-logs",
  // Hyper Liquid Data Pipeline (Local → Marketplace)
  "hyper-liquid:get-pipelines",
  "hyper-liquid:get-pipeline",
  "hyper-liquid:create-pipeline",
  "hyper-liquid:update-pipeline",
  "hyper-liquid:delete-pipeline",
  "hyper-liquid:start-pipeline",
  "hyper-liquid:stop-pipeline",
  "hyper-liquid:pause-pipeline",
  "hyper-liquid:resume-pipeline",
  "hyper-liquid:start-flow",
  "hyper-liquid:batch-flow",
  "hyper-liquid:get-flow",
  "hyper-liquid:get-flows",
  "hyper-liquid:cancel-flow",
  "hyper-liquid:retry-flow",
  "hyper-liquid:get-queue",
  "hyper-liquid:get-queues",
  "hyper-liquid:get-stats",
  "hyper-liquid:reset-stats",
  "hyper-liquid:check-dedup",
  "hyper-liquid:get-checkpoint",
  "hyper-liquid:resume-from-checkpoint",
  "hyper-liquid:status",
  // OpenClaw Gateway - Local AI Gateway with n8n integration
  "openclaw:initialize",
  "openclaw:shutdown",
  "openclaw:gateway:start",
  "openclaw:gateway:stop",
  "openclaw:gateway:status",
  "openclaw:system-info",
  "openclaw:config:get",
  "openclaw:config:update",
  "openclaw:gateway-token",
  "openclaw:claude-code:config:get",
  "openclaw:claude-code:config:update",
  "openclaw:provider:list",
  "openclaw:provider:health",
  "openclaw:provider:configure",
  "openclaw:provider:remove",
  "openclaw:provider:set-api-key",
  "openclaw:chat",
  "openclaw:chat:stream",
  "openclaw:agent:execute-task",
  "openclaw:agent:execute-with-n8n",
  "openclaw:claude-code:execute",
  "openclaw:claude-code:batch",
  "openclaw:n8n:trigger-workflow",
  "openclaw:n8n:create-agent-workflow",
  "openclaw:autonomous:create-app",
  "openclaw:autonomous:refactor-code",
  "openclaw:autonomous:analyze-codebase",
  "openclaw:quick:generate-code",
  "openclaw:quick:explain-code",
  "openclaw:quick:fix-error",
  "openclaw:subscribe",
  "openclaw:unsubscribe",
  // OpenClaw Autonomous Brain — Cross-feature AI orchestration
  "openclaw:autonomous:execute",
  "openclaw:autonomous:plan",
  "openclaw:autonomous:approve",
  "openclaw:autonomous:cancel",
  "openclaw:autonomous:get",
  "openclaw:autonomous:list",
  "openclaw:autonomous:status",
  "openclaw:autonomous:actions",
  // OpenClaw Cost Engine - Smart cost tracking & budget
  "openclaw:cost:summary",
  "openclaw:cost:records",
  "openclaw:cost:budget:get",
  "openclaw:cost:budget:set",
  "openclaw:cost:estimate",
  "openclaw:cost:check-budget",
  "openclaw:cost:task-routing:get",
  "openclaw:cost:task-routing:set",
  "openclaw:cost:task-routing:reset",
  "openclaw:cost:tiered-routing:get",
  "openclaw:cost:tiered-routing:set",
  // OpenClaw Data Pipeline - Scraping, Data Collection & Image Generation
  "openclaw:data:initialize",
  "openclaw:data:scrape",
  "openclaw:data:scrape:single",
  "openclaw:data:image:generate",
  "openclaw:data:image:enhance-prompt",
  "openclaw:data:pipeline:run",
  "openclaw:data:request",
  "openclaw:data:jobs:list",
  "openclaw:data:jobs:get",
  "openclaw:data:jobs:cancel",
  "openclaw:data:events:subscribe",
  "openclaw:data:events:unsubscribe",
  // OpenClaw System Integration - Unified AI gateway across all systems
  "openclaw:system:initialize",
  "openclaw:system:config:get",
  "openclaw:system:config:update",
  "openclaw:system:stats",
  "openclaw:system:history",
  "openclaw:system:execute",
  "openclaw:system:chat",
  "openclaw:system:agent-inference",
  "openclaw:system:events:subscribe",
  // OpenClaw Local AI Hub Integration
  "openclaw:local-hub:status",
  "openclaw:local-hub:chat",
  "openclaw:local-hub:combined-stats",
  // Studio AI Service (Claude Code + Ollama Integration)
  "studio-ai:initialize",
  "studio-ai:config:get",
  "studio-ai:config:update",
  "studio-ai:stats",
  "studio-ai:execute",
  "studio-ai:data:generate-items",
  "studio-ai:data:augment",
  "studio-ai:data:analyze",
  "studio-ai:document:generate",
  "studio-ai:document:enhance",
  "studio-ai:asset:generate-code",
  "studio-ai:asset:generate-schema",
  "studio-ai:asset:analyze-code",
  "studio-ai:asset:refactor-code",
  "studio-ai:asset:generate-tests",
  "studio-ai:swarm:generate-agent-config",
  "studio-ai:swarm:execute-task",
  "studio-ai:swarm:coordinate",
  "studio-ai:swarm:optimize-agent",
  "studio-ai:dataset:generate-qa-pairs",
  "studio-ai:dataset:generate-conversations",
  "studio-ai:dataset:generate-classification-data",
  // 🦞 OpenClaw Personal AI Assistant Integration
  // Multi-channel messaging (WhatsApp, Telegram, Slack, Discord, Signal, iMessage, etc.)
  // AI agents with thinking levels, memory search, plugin management
  // EXFOLIATE! EXFOLIATE!
  "openclaw:gateway:health",
  "openclaw:gateway:restart",
  "openclaw:gateway:yield-to-daemon",
  "openclaw:daemon:autostart-status",
  "openclaw:daemon:autostart-set",
  "openclaw:connection:status",
  "openclaw:agent:run",
  "openclaw:message:send",
  "openclaw:message:broadcast",
  "openclaw:message:read",
  "openclaw:memory:search",
  "openclaw:channels:list",
  "openclaw:channels:configure",
  "openclaw:plugins:list",
  "openclaw:plugins:install",
  "openclaw:plugins:uninstall",
  "openclaw:plugins:enable",
  "openclaw:plugins:disable",
  "openclaw:doctor",
  // OpenClaw Kanban — Task board CRUD + analytics
  "openclaw:kanban:tasks:list",
  "openclaw:kanban:tasks:get",
  "openclaw:kanban:tasks:create",
  "openclaw:kanban:tasks:update",
  "openclaw:kanban:tasks:delete",
  "openclaw:kanban:tasks:move",
  "openclaw:kanban:activity:list",
  "openclaw:kanban:analytics",
  "openclaw:kanban:models:list",
  "openclaw:kanban:tasks:rate",
  // OpenClaw Activity Log — persistent bot activity & channel messages
  "openclaw:activity:log",
  "openclaw:activity:log-batch",
  "openclaw:activity:list",
  "openclaw:activity:stats",
  "openclaw:activity:message:save",
  "openclaw:activity:messages:list",
  // Telegram Bot — Native Telegram integration
  "telegram:configure",
  "telegram:validate-token",
  "telegram:start",
  "telegram:stop",
  "telegram:status",
  "telegram:config",
  "telegram:send-message",
  // Discord Bot — Native Discord integration
  "discord:configure",
  "discord:validate-token",
  "discord:start",
  "discord:stop",
  "discord:status",
  "discord:config",
  "discord:send-message",
  // Task Executor — Autonomous inference loop
  "task-executor:status",
  "task-executor:start",
  "task-executor:stop",
  // System Services Health
  "system:services-health",
  "system:celestia:start",
  "system:celestia:stop",
  "system:celestia:status",
  // 🦞 OpenClaw CNS (Central Nervous System) - Ollama & N8n Integration
  // Unified AI routing with local (Ollama) and cloud (Anthropic) backends
  "cns:initialize",
  "cns:shutdown",
  "cns:status",
  "cns:config:get",
  "cns:config:update",
  "cns:process",
  "cns:chat",
  "cns:agent-task",
  // CNS Ollama Bridge
  "cns:ollama:status",
  "cns:ollama:health",
  "cns:ollama:models",
  "cns:ollama:inference",
  "cns:ollama:embed",
  "cns:ollama:recommend-model",
  "cns:ollama:performance",
  "cns:ollama:config:update",
  // CNS N8n Bridge
  "cns:n8n:status",
  "cns:n8n:connections",
  "cns:n8n:add-connection",
  "cns:n8n:remove-connection",
  "cns:n8n:test-connection",
  "cns:n8n:workflows",
  "cns:n8n:workflow",
  "cns:n8n:trigger-workflow",
  "cns:n8n:register-webhook",
  "cns:n8n:unregister-webhook",
  "cns:n8n:config:update",
  // Local Vault — Sovereign local-first data vault
  "local-vault:status",
  "local-vault:initialize",
  "local-vault:unlock",
  "local-vault:lock",
  "local-vault:get-config",
  "local-vault:update-config",
  "local-vault:connector:list",
  "local-vault:connector:get",
  "local-vault:connector:add",
  "local-vault:connector:update",
  "local-vault:connector:remove",
  "local-vault:connector:enable",
  "local-vault:connector:disable",
  "local-vault:import:file",
  "local-vault:import:files-dialog",
  "local-vault:import:folder",
  "local-vault:import:folder-dialog",
  "local-vault:import:text",
  "local-vault:import:dataset-items",
  "local-vault:asset:list",
  "local-vault:asset:get",
  "local-vault:asset:content",
  "local-vault:asset:update",
  "local-vault:asset:delete",
  "local-vault:transform:create",
  "local-vault:transform:get",
  "local-vault:transform:list",
  "local-vault:transform:run",
  "local-vault:package:create",
  "local-vault:package:list",
  "local-vault:package:get",
  "local-vault:policy:create",
  "local-vault:policy:get",
  "local-vault:policy:get-by-manifest",
  "local-vault:publish:create-bundle",
  "local-vault:publish:list-bundles",
  "local-vault:publish:get-bundle",
  "local-vault:audit:list",
  // Multi-Armed Bandit Learning — Thompson Sampling continuous improvement
  "mab:arm:create",
  "mab:arm:get",
  "mab:arm:list",
  "mab:arm:update",
  "mab:arm:delete",
  "mab:arm:reset",
  "mab:arm:get-or-create",
  "mab:select",
  "mab:reward",
  "mab:reward:by-name",
  "mab:reward:history",
  "mab:reward:recent",
  "mab:decay:apply",
  "mab:decay:get-config",
  "mab:decay:set-config",
  "mab:stats",
  "mab:context-keys",
  // ── Agent Builder System (full) ──
  "agent-builder:create-agent",
  "agent-builder:create-from-template",
  "agent-builder:get-agent",
  "agent-builder:list-agents",
  "agent-builder:update-agent",
  "agent-builder:delete-agent",
  "agent-builder:activate-agent",
  "agent-builder:add-tool",
  "agent-builder:update-tool",
  "agent-builder:remove-tool",
  "agent-builder:list-builtin-tools",
  "agent-builder:execute-agent",
  "agent-builder:get-execution",
  "agent-builder:list-executions",
  "agent-builder:create-session",
  "agent-builder:get-session",
  "agent-builder:clear-session",
  "agent-builder:end-session",
  "agent-builder:create-team",
  "agent-builder:list-teams",
  "agent-builder:execute-team",
  "agent-builder:list-templates",
  "agent-builder:get-template",
  "agent-builder:save-as-template",
  "agent-builder:get-agent-stats",
  "agent-builder:get-global-stats",
  // ── Analytics Reporting ──
  "analytics:dataset",
  "analytics:global",
  "analytics:time-series",
  "analytics:compare-datasets",
  "analytics:generate-report",
  "analytics:list-reports",
  "analytics:get-report",
  "analytics:delete-report",
  "analytics:get-dashboard",
  "analytics:update-dashboard",
  "analytics:create-dashboard",
  "analytics:clear-cache",
  // ── Annotation System ──
  "annotation:create-taxonomy",
  "annotation:list-taxonomies",
  "annotation:get-taxonomy",
  "annotation:update-taxonomy",
  "annotation:add-label",
  "annotation:delete-taxonomy",
  "annotation:create-task",
  "annotation:list-tasks",
  "annotation:get-task",
  "annotation:update-task-status",
  "annotation:get-next-item",
  "annotation:submit",
  "annotation:skip-item",
  "annotation:review",
  "annotation:get-item-annotations",
  "annotation:list-templates",
  "annotation:create-template",
  "annotation:get-annotator-stats",
  "annotation:calculate-agreement",
  "annotation:export",
  "annotation:import",
  // ── Data Studio Core ──
  "data-studio:batch-import-directory",
  "data-studio:import-jsonl",
  "data-studio:import-csv",
  "data-studio:export-to-format",
  "data-studio:validate-dataset",
  "data-studio:find-duplicates",
  "data-studio:remove-duplicates",
  "data-studio:create-backup",
  "data-studio:restore-backup",
  "data-studio:list-backups",
  "data-studio:advanced-search",
  "data-studio:get-statistics",
  // ── Data Vault ──
  "data-vault:status",
  "data-vault:initialize",
  "data-vault:unlock",
  "data-vault:lock",
  "data-vault:change-passphrase",
  "data-vault:get-identity",
  "data-vault:sign",
  "data-vault:verify",
  "data-vault:store-secret",
  "data-vault:get-secret",
  "data-vault:delete-secret",
  "data-vault:list-secrets",
  "data-vault:add-peer",
  "data-vault:remove-peer",
  "data-vault:update-peer",
  "data-vault:list-peers",
  "data-vault:get-peer-by-key",
  "data-vault:encrypt-for-peer",
  "data-vault:decrypt-from-peer",
  "data-vault:export-identity",
  "data-vault:export-backup",
  "data-vault:export",
  // ── Data Generation ──
  "generation:list-templates",
  "generation:get-template",
  "generation:create-template",
  "generation:update-template",
  "generation:delete-template",
  "generation:generate-single",
  "generation:start-batch",
  "generation:get-job-status",
  "generation:cancel-job",
  "generation:augment-item",
  "generation:augment-dataset",
  "generation:create-hybrid",
  "generation:generate-variables",
  // ── Data Lineage ──
  "lineage:register-node",
  "lineage:create-edge",
  "lineage:record-transformation",
  "lineage:get-item-lineage",
  "lineage:get-dataset-lineage",
  "lineage:query",
  "lineage:impact-analysis",
  "lineage:find-common-ancestors",
  "lineage:get-audit-trail",
  "lineage:export",
  "lineage:clear",
  // ── Data Scraping ──
  "scraping:scrape-to-dataset",
  "scraping:scrape-feed-to-dataset",
  "scraping:scrape-api",
  "scraping:extract-urls",
  // ── Data Transformation ──
  "transform:export-dataset",
  "transform:list-templates",
  "transform:create-structure",
  "transform:convert-format",
  "transform:tokenize",
  "transform:build-vocab",
  "transform:prepare-training",
  "transform:get-stats",
  // ── Fulltext Search ──
  "search:index-item",
  "search:index-dataset",
  "search:remove-from-index",
  "search:get-index-stats",
  "search:query",
  "search:suggestions",
  "search:fuzzy",
  "search:save",
  "search:list-saved",
  "search:delete-saved",
  "search:execute-saved",
  "search:get-analytics",
  "search:record-click",
  "search:clear-history",
  "search:get-facets",
  "search:rebuild-index",
  // ── Media Pipeline ──
  "media-pipeline:get-info",
  "media-pipeline:check-tools",
  "media-pipeline:process-image",
  "media-pipeline:generate-thumbnail",
  "media-pipeline:extract-image-metadata",
  "media-pipeline:strip-metadata",
  "media-pipeline:process-audio",
  "media-pipeline:extract-waveform",
  "media-pipeline:process-video",
  "media-pipeline:extract-frames",
  "media-pipeline:detect-scenes",
  "media-pipeline:video-thumbnail",
  "media-pipeline:batch-process",
  "media-pipeline:cleanup-temp",
  // ── n8n Integration v2 ──
  "n8n:get-config",
  "n8n:update-config",
  "n8n:add-connection",
  "n8n:test-connection",
  "n8n:list-connections",
  "n8n:remove-connection",
  "n8n:list-workflows",
  "n8n:get-workflow",
  "n8n:create-workflow",
  "n8n:execute-workflow",
  "n8n:create-webhook",
  "n8n:list-webhooks",
  "n8n:delete-webhook",
  "n8n:toggle-webhook",
  "n8n:get-webhook-history",
  "n8n:create-mapping",
  "n8n:list-mappings",
  "n8n:sync-mapping",
  "n8n:list-templates",
  "n8n:deploy-template",
  "n8n:start-server",
  "n8n:stop-server",
  "n8n:get-server-status",
  "n8n:subscribe-events",
  // ── Orchestrator Core ──
  "orchestrator:create-workflow",
  "orchestrator:get-workflow",
  "orchestrator:list-workflows",
  "orchestrator:update-workflow",
  "orchestrator:delete-workflow",
  "orchestrator:activate-workflow",
  "orchestrator:pause-workflow",
  "orchestrator:execute-workflow",
  "orchestrator:get-execution",
  "orchestrator:list-executions",
  "orchestrator:cancel-execution",
  "orchestrator:pause-execution",
  "orchestrator:resume-execution",
  "orchestrator:schedule-workflow",
  "orchestrator:list-schedules",
  "orchestrator:update-schedule",
  "orchestrator:delete-schedule",
  "orchestrator:emit-event",
  "orchestrator:list-events",
  "orchestrator:get-metrics",
  "orchestrator:get-node-types",
  // ── Pipeline Automation ──
  "pipeline:create",
  "pipeline:create-from-template",
  "pipeline:list",
  "pipeline:get",
  "pipeline:update",
  "pipeline:delete",
  "pipeline:run",
  "pipeline:cancel",
  "pipeline:get-run",
  "pipeline:list-runs",
  "pipeline:add-trigger",
  "pipeline:update-trigger",
  "pipeline:remove-trigger",
  "pipeline:list-templates",
  "pipeline:save-template",
  "pipeline:get-step-types",
  // ── Policy Engine ──
  "policy:create",
  "policy:list",
  "policy:get",
  "policy:update",
  "policy:delete",
  "policy:evaluate-item",
  "policy:scan-dataset",
  "policy:list-licenses",
  "policy:get-license",
  "policy:add-license",
  "policy:validate-license-compatibility",
  "policy:set-dataset-license",
  "policy:list-privacy-rules",
  "policy:add-privacy-rule",
  "policy:update-privacy-rule",
  "policy:delete-privacy-rule",
  "policy:scan-pii",
  "policy:redact-pii",
  "policy:scan-dataset-pii",
  "policy:create-retention",
  "policy:list-retention",
  "policy:execute-retention",
  "policy:list-violations",
  "policy:resolve-violation",
  "policy:clear-resolved-violations",
  // ── Quality Analysis ──
  "quality:analyze-image",
  "quality:compute-phash",
  "quality:analyze-text",
  "quality:find-exact-duplicates",
  "quality:find-similar-images",
  "quality:batch-analyze",
  "quality:get-statistics",
  "quality:filter-items",
  // ── Schema Validation ──
  "schema:create",
  "schema:create-from-template",
  "schema:list",
  "schema:get",
  "schema:update",
  "schema:delete",
  "schema:validate-item",
  "schema:validate-dataset",
  "schema:get-report",
  "schema:list-reports",
  "schema:infer",
  "schema:list-templates",
  "schema:get-categories",
  "schema:add-rule",
  "schema:remove-rule",
  "schema:export",
  "schema:import",
  // ── Task Execution Engine ──
  "task-engine:create-task",
  "task-engine:create-from-template",
  "task-engine:get-task",
  "task-engine:list-tasks",
  "task-engine:cancel-task",
  "task-engine:retry-task",
  "task-engine:create-queue",
  "task-engine:list-queues",
  "task-engine:get-queue",
  "task-engine:pause-queue",
  "task-engine:resume-queue",
  "task-engine:create-batch",
  "task-engine:get-batch",
  "task-engine:list-batches",
  "task-engine:list-templates",
  "task-engine:get-metrics",
  // ── Version Control ──
  "version:commit",
  "version:list",
  "version:get",
  "version:tag",
  "version:find-by-tag",
  "version:create-branch",
  "version:list-branches",
  "version:delete-branch",
  "version:protect-branch",
  "version:diff",
  "version:diff-branches",
  "version:rollback",
  "version:cherry-pick",
  "version:merge",
  "version:timeline",
  "version:graph",
  // Data Flywheel — Self-reinforcing training loop
  "flywheel:capture-pair",
  "flywheel:rate-message",
  "flywheel:correct-message",
  "flywheel:get-stats",
  "flywheel:get-runs",
  "flywheel:run-cycle",
  "flywheel:run-scheduled",
  "flywheel:register-n8n-workflow",
  "flywheel:remove-n8n-workflow",
  // Decentralized Model Registry
  "model-registry:register",
  "model-registry:register-adapter",
  "model-registry:get",
  "model-registry:search",
  "model-registry:list-local",
  "model-registry:publish",
  "model-registry:rate",
  "model-registry:mab-signal",
  "model-registry:record-usage",
  "model-registry:update",
  "model-registry:delete",
  "model-registry:delist",
  "model-registry:stats",
  "model-registry:get-ratings",
  "model-registry:list-peers",
  "model-registry:download",
  "model-registry:download-status",
  "model-registry:list-downloads",
  // MCP Server
  "mcp-server:start",
  "mcp-server:stop",
  "mcp-server:status",
  "mcp-server:get-config",
  // Test-only channels
  // These should ALWAYS be guarded with IS_TEST_BUILD in the main process.
  // We can't detect with IS_TEST_BUILD in the preload script because
  // it's a separate process from the main process.
  "supabase:fake-connect-and-set-project",
  // Neural Network Builder
  "neural:list-networks",
  "neural:create-network",
  "neural:get-network",
  "neural:update-network",
  "neural:delete-network",
  "neural:add-layer",
  "neural:update-layer",
  "neural:remove-layer",
  "neural:reorder-layers",
  "neural:start-training",
  "neural:stop-training",
  "neural:list-versions",
  "neural:create-version",
  "neural:rollback-version",
  "neural:delete-version",
  "neural:list-ab-tests",
  "neural:create-ab-test",
  "neural:delete-ab-test",
  "neural:list-pretrained-models",
  "neural:apply-transfer-learning",
  "neural:automl-optimize",
  "neural:configure-edge-deployment",
  "neural:deploy-to-edge",
  "neural:get-analytics",
  "neural:export-model",
  // CI/CD Pipeline Builder
  "cicd:get-templates",
  "cicd:list-pipelines",
  "cicd:get-pipeline",
  "cicd:create-pipeline",
  "cicd:update-pipeline",
  "cicd:delete-pipeline",
  "cicd:create-from-template",
  "cicd:add-step",
  "cicd:update-step",
  "cicd:remove-step",
  "cicd:reorder-steps",
  "cicd:run-pipeline",
  "cicd:cancel-run",
  "cicd:list-runs",
  "cicd:get-run",
  "cicd:get-run-logs",
  "cicd:delete-run",
  // Calendar — source management, events, sync, agent scheduling
  "calendar:list-sources",
  "calendar:add-source",
  "calendar:update-source",
  "calendar:remove-source",
  "calendar:test-source",
  "calendar:sync-source",
  "calendar:sync-all",
  "calendar:list-calendars",
  "calendar:list-events",
  "calendar:get-event",
  "calendar:create-event",
  "calendar:update-event",
  "calendar:delete-event",
  "calendar:schedule-agent-event",
  "calendar:list-agent-events",
  "calendar:export-ics",
  // Skill System — reusable, marketplace-sellable skills
  "skill:create",
  "skill:get",
  "skill:list",
  "skill:update",
  "skill:delete",
  "skill:search",
  "skill:match",
  "skill:execute",
  "skill:generate",
  "skill:auto-generate",
  "skill:attach-to-agent",
  "skill:detach-from-agent",
  "skill:list-for-agent",
  "skill:publish",
  "skill:unpublish",
  "skill:export",
  "skill:import",
  "skill:export-md",
  "skill:bootstrap",
  "skill:learn",
];

// Add valid receive channels
const validReceiveChannels = [
  "chat:response:chunk",
  "chat:response:end",
  "chat:response:error",
  "chat:agent-blueprint",
  "app:output",
  "github:flow-update",
  "github:flow-success",
  "github:flow-error",
  "deep-link-received",
  "force-close-detected",
  // Auto-Deploy progress events
  "auto-deploy:progress",
  // Help bot
  "help:chat:response:chunk",
  "help:chat:response:end",
  "help:chat:response:error",
  // Joy Assistant
  "joy-assistant:response:chunk",
  "joy-assistant:response:end",
  "joy-assistant:response:error",
  // MCP consent request from main to renderer
  "mcp:tool-consent-request",
  // Agent tool consent request from main to renderer
  "agent-tool:consent-request",
  // Telemetry events from main to renderer
  "telemetry:event",
  // Voice Assistant events
  "voice:event",
  // Memory System events
  "memory:event",
  // Plugin System events
  "plugin:event",
  // Model Benchmark events
  "benchmark:event",
  // AI Coding Agent events
  "coding-agent:event",
  // Design System Generator events
  "design-system:event",
  // Secrets Vault events
  "secrets-vault:event",
  // Offline Docs Hub events
  "offline-docs:event",
  // Federation inference streaming
  "federation:inference:chunk",
  "federation:inference:done",
  "federation:inference:error",
  // Hybrid Bridge events
  "hybrid-bridge:event",
  // Decentralized Chat events
  "decentralized-chat:event",
  // Compute Network events
  "compute-network:event",
  // WebRTC events
  "webrtc:event",
  // JCN events (publish progress, job completion, etc.)
  "jcn:event",
  // Smart Router events
  "smart-router:event",
  // AI Learning Mode events
  "ai-learning:event",
  // Agent Swarm System events
  "agent-swarm:event",
  "agent-swarm:task-progress",
  // Autonomous Agent System events
  "autonomous-agent:event",
  "autonomous-agent:inference-request",
  // Autonomous Agent Production System events
  "autonomous-prod:event",
  // Model Factory training events
  "model-factory:training-progress",
  "model-factory:training-completed",
  // HuggingFace Hub events
  "hf:download-progress",
  // Agent Factory events
  "agent-factory:event",
  // Hyper Liquid Data Pipeline events
  "hyper-liquid:event",
  "hyper-liquid:progress",
  // OpenClaw Gateway events
  "openclaw:event",
  "openclaw:chat:stream-chunk",
  // OpenClaw Data Pipeline events
  "openclaw:data:event",
  // OpenClaw System Integration events
  "openclaw:system:event",
  // 🦞 OpenClaw Personal AI Assistant events
  "openclaw:event:connected",
  "openclaw:event:disconnected",
  "openclaw:event:error",
  "openclaw:event:gateway-started",
  "openclaw:event:gateway-stopped",
  "openclaw:event:gateway-restarted",
  "openclaw:event:agent-thinking",
  "openclaw:event:agent-tool-call",
  "openclaw:event:agent-response",
  "openclaw:event:agent-completed",
  "openclaw:event:message-received",
  "openclaw:event:message-sent",
  "openclaw:event:channel-connected",
  "openclaw:event:channel-disconnected",
  "openclaw:event:plugin-installed",
  "openclaw:event:plugin-uninstalled",
  "openclaw:event:plugin-enabled",
  "openclaw:event:plugin-disabled",
  "openclaw:event:config-updated",
  "openclaw:event:reconnect-failed",
  "openclaw:event:warning",
  // 🦞 OpenClaw CNS (Central Nervous System) events
  "cns:event:initialized",
  "cns:event:shutdown",
  "cns:event:request:start",
  "cns:event:request:complete",
  "cns:event:request:error",
  "cns:event:message:received",
  "cns:event:agent:completed",
  "cns:event:workflow:triggering",
  "cns:event:workflow:failed",
  "cns:event:ollama:connected",
  "cns:event:ollama:disconnected",
  "cns:event:ollama:inference:start",
  "cns:event:ollama:inference:complete",
  "cns:event:ollama:inference:chunk",
  "cns:event:ollama:inference:error",
  "cns:event:ollama:models:refreshed",
  "cns:event:n8n:connection:added",
  "cns:event:n8n:connection:removed",
  "cns:event:n8n:webhook:registered",
  "cns:event:n8n:webhook:unregistered",
  "cns:event:n8n:event:triggered",
  "cns:event:n8n:event:failed",
  // Studio AI Service events
  "studio-ai:event",
  "studio-ai:chat:stream-chunk",
  // Scraping Engine v2 progress events
  "scraping:job-progress",
  // Scraping Engine v3 progress events
  "scraping:v3:job-progress",
  "scraping:captcha-required",
  // Agent Orchestrator events
  "orchestrator:event",
  // Agent execution events
  "agent:execution-completed",
  // Model Manager events
  "model-manager:pull-progress",
  "model-manager:pull-complete",
  // Email Agent System events
  "email:sync-event",
  "email:pending-action",
  "email:orchestrator-status",
  "email:daily-digest-ready",
  // LibreOffice streaming document generation
  "libreoffice:generate-chunk",
  // LibreOffice AI editing assist
  "libreoffice:ai-assist-chunk",
  // Neural Network Builder — streaming training events
  "neural:training-progress",
  "neural:training-complete",
  "neural:training-error",
  "neural:automl-progress",
  "neural:automl-complete",
  // CI/CD Pipeline Builder — streaming run events
  "cicd:run-progress",
  "cicd:log-line",
  "cicd:run-complete",
  // Calendar — sync progress events
  "calendar:sync-progress",
  "calendar:sync-complete",
] as const;

type ValidInvokeChannel = (typeof validInvokeChannels)[number];
type ValidReceiveChannel = (typeof validReceiveChannels)[number];

// Expose protected methods that allow the renderer process to use
// the ipcRenderer without exposing the entire object
contextBridge.exposeInMainWorld("electron", {
  ipcRenderer: {
    invoke: (channel: ValidInvokeChannel, ...args: unknown[]) => {
      if (validInvokeChannels.includes(channel)) {
        return ipcRenderer.invoke(channel, ...args);
      }
      throw new Error(`Invalid channel: ${channel}`);
    },
    on: (
      channel: ValidReceiveChannel,
      listener: (...args: unknown[]) => void,
    ) => {
      if (validReceiveChannels.includes(channel)) {
        const subscription = (
          _event: Electron.IpcRendererEvent,
          ...args: unknown[]
        ) => listener(...args);
        ipcRenderer.on(channel, subscription);
        return () => {
          ipcRenderer.removeListener(channel, subscription);
        };
      }
      throw new Error(`Invalid channel: ${channel}`);
    },
    removeAllListeners: (channel: ValidReceiveChannel) => {
      if (validReceiveChannels.includes(channel)) {
        ipcRenderer.removeAllListeners(channel);
      }
    },
    removeListener: (
      channel: ValidReceiveChannel,
      listener: (...args: unknown[]) => void,
    ) => {
      if (validReceiveChannels.includes(channel)) {
        ipcRenderer.removeListener(channel, listener);
      }
    },
  },
  webFrame: {
    setZoomFactor: (factor: number) => {
      webFrame.setZoomFactor(factor);
    },
    getZoomFactor: () => webFrame.getZoomFactor(),
  },
});
